import { frameworkBaseGame } from "../../../core/components/basegame/configuration/basegameconfiguration"
import { basegameAssetConfig } from "../../../data/basegame/index";
import { objectTypes } from "../../../core/components/buttonpanel/interface/Ibuttons";


frameworkBaseGame.data = {

    "POS_X": 0,
    "POS_Y": 0,
    "COMPONENTS": [
        {
            "id": "BMBaseGameContainer_baseLayer",
            "name": "BMBaseGameContainer_baseLayer",
            "type": "Container",
            "class": "",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "parentLayer": "baseLayer",
            child: [
                {
                    "id": "BMBaseGameComponent",
                    "name": "GofBaseGame",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [

                        {
                            "name": "BG_reelOfFrame_Image_Desktop",
                            "image": "Bg_reelImage",
                            "type": "Image",
                            "layout": false,
                            "uimode": "desktop",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 654,
                            "height": 430,
                            "x": 981,
                            "y": 518
                        },
                        {
                            "name": "BG_reelOfFrame_Image_Mobile",
                            "image": "Bg_reelImage",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 654,
                            "height": 430,

                            "x": 959.5,
                            "y": 502.5
                        },


                    ]
                }
            ]
        },
        {
            "id": "BMBaseGameContainer_specialLayer",
            "name": "BMBaseGameContainer_specialLayer",
            "type": "Container",
            "class": "",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "parentLayer": "specialAnimationLayer",
            child: [
                {
                    "id": "BMBaseGameComponent",
                    "name": "GofBaseGame",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [

                        {
                            "name": "BG_frame_Image_Desktop",
                            "image": "Bg_frame",
                            "type": "Image",
                            "layout": true,
                            "uimode": "desktop",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 1924,
                            "height": 1084,
                            "x": 957.5,
                            "y": 542.5
                        },
                        {
                            "name": "BG_frame_Image_Mobile",
                            "image": "Bg_frame",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 1859,
                            "height": 1008,
                            "x": 959.5,
                            "y": 502.5
                        },

                        {
                            "name": "BG_textManyWays_Image_Desktop",
                            "image": "manywaysTextImage",
                            "type": "Image",
                            "layout": true,
                            "uimode": "desktop",
                            "class": "",
                            "parentLayer": "baseLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 131,
                            "height": 43,
                            "x": 1028,
                            "y": 44,
                        },
                        {
                            "name": "BG_textManyWays_Image_mobile",
                            "image": "manywaysTextImage",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "class": "",
                            "parentLayer": "baseLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 131,
                            "height": 43,
                            "x": 1028,
                            "y": 44,
                        },

                        {
                            "id": "BG_leftTorchFlame_Anim_desktop",
                            "name": "BG_leftTorchFlame_Anim_desktop",
                            "type": "Spine",
                            "x": 135,
                            "y": 725,
                            "width": 46,
                            "height": 49,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "anchor": [0, 0],
                            "spinedata": {
                                "spinename": "bg_left_torch_flame",
                                "animationname": "loop",
                                "loop": true,
                                "timeScale": 0.5

                            },
                        },
                        {
                            "id": "BG_leftTorchFlame_Anim_mobile",
                            "name": "BG_leftTorchFlame_Anim_mobile",
                            "type": "Spine",
                            "x": 135,
                            "y": 725,
                            "width": 46,
                            "height": 49,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "anchor": [0, 0],
                            "spinedata": {
                                "spinename": "bg_left_torch_flame",
                                "animationname": "loop",
                                "loop": true,
                                "timeScale": 0.5

                            },
                        },

                        {
                            "id": "BG_rightTorchFlame_Anim_desktop",
                            "name": "BG_rightTorchFlame_Anim_desktop",
                            "type": "Spine",
                            "x": 1778,
                            "y": 725,
                            "width": 46,
                            "height": 49,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "anchor": [0, 0],
                            "spinedata": {
                                "spinename": "bg_left_torch_flame",
                                "animationname": "loop",
                                "loop": true,
                                "timeScale": 0.5

                            },
                        },

                        {
                            "id": "BG_rightTorchFlame_Anim_mobile",
                            "name": "BG_rightTorchFlame_Anim_mobile",
                            "type": "Spine",
                            "x": 1778,
                            "y": 725,
                            "width": 46,
                            "height": 49,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "anchor": [0, 0],
                            "spinedata": {
                                "spinename": "bg_left_torch_flame",
                                "animationname": "loop",
                                "loop": true,
                                "timeScale": 0.5

                            },
                        },

                        {
                            "name": "BG_gameLogo_Anim_desktop",
                            "type": "Animation",
                            "width": 162,
                            "height": 167,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "bg_gamelogo.png",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.25,
                            "playing": false,
                            "loop": false,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 128.5,
                            "y": 186.5,
                            "animations": {
                                "anim": ["bg_gamelogo"],
                            },
                        },
                        {
                            "name": "BG_gameLogo_Anim_mobile",
                            "type": "Animation",
                            "width": 162,
                            "height": 167,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "bg_gamelogo.png",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.3,
                            "playing": false,
                            "loop": false,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 128.5,
                            "y": 186.5,
                            "animations": {
                                "anim": ["bg_gamelogo"],
                            },
                        },

                        {
                            "name": "mobileViewBottomBArImage1",
                            "image": "mobileViewBottomBarImage1",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "filterTypes": [],
                            "visible": true,
                            "width": 1920,
                            "height": 150,
                            "x": 0,
                            "y": 872
                        },
                        {
                            "name": "mobileViewBottomBArImage2",
                            "image": "mobileViewBottomBarImage2",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "filterTypes": [],
                            "visible": true,
                            "width": 1920,
                            "height": 70,
                            "x": 0,
                            "y": 1010
                        },

                        {
                            "id": "BG_BitMapText_1_desktop",
                            "name": "BG_manywaysText_desktop",
                            "type": "BitMapText",
                            "x": 965,
                            "y": -152,
                            "width": 180,
                            "text": "0",
                            "visible": true,
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "layout": true,
                            "uimode": "desktop",
                            "textStyle": {
                                font: '439px num-export',
                                letterSpacing: -15,
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "BG_BitMapText_1_mobile",
                            "name": "BG_manywaysText_mobile",
                            "type": "BitMapText",
                            "x": 560,
                            "y": 10,
                            "width": 180,
                            "text": "0",
                            "visible": true,
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "layout": true,
                            "uimode": "mobile",
                            "textStyle": {
                                font: '439px num-export',
                                letterSpacing: -15,
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "BMHorizontalGridContainerTag",
                            "name": "HorizontalGridContainer",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            "x": 0,
                            "y": 0,
                            child: []
                        },
                        {
                            "name": "leftCaveMaskImage_desktop",
                            "image": "leftCaveMask",
                            "type": "Image",
                            "class": "",
                            "layout": false,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "desktop",
                            "filterTypes": [],
                            "visible": true,
                            "width": 161,
                            "height": 190,
                            "x": 356,
                            "y": 63
                        },
                        {
                            "name": "rightCaveMaskImage_desktop",
                            "image": "rightCaveMask",
                            "type": "Image",
                            "class": "",
                            "layout": false,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "desktop",
                            "filterTypes": [],
                            "visible": true,
                            "width": 161,
                            "height": 190,
                            "x": 1404,
                            "y": 63
                        },
                        {
                            "name": "leftCaveMaskImage_mobile",
                            "image": "leftCaveMask",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "filterTypes": [],
                            "visible": true,
                            "width": 161,
                            "height": 190,
                            "x": 356,
                            "y": 63
                        },
                        {
                            "name": "rightCaveMaskImage_mobile",
                            "image": "rightCaveMask",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "filterTypes": [],
                            "visible": true,
                            "width": 161,
                            "height": 190,
                            "x": 1404,
                            "y": 63
                        },
                        {
                            "id": "winCelebrationContainerTag",
                            "name": "WinCelebration",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                        {
                            "id": "winShowerContainerTag",
                            "name": "WinShower",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },

                        {
                            "id": "BG_win_Text_Bg_Image",
                            "name": "BG_win_Text_Bg_Image",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "interactive": false,
                            "x": 1221,
                            "y": 929,
                            "width": 262,
                            "height": 68,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'win.png',
                                out: 'win.png',
                                down: 'win.png',
                                disable: 'win.png',
                                enable: 'win.png',
                                hover: 'win.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "text_5",
                            "name": "text_win_label",
                            "type": "Text",
                            "uimode": "desktop",
                            "x": 1350,
                            "y": 910,
                            "width": 200,
                            "visible": true,
                            "text": "buttonPanelText_5",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 27,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],

                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_6",
                            "name": "text_win_value1",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 1350,
                            "y": 964.5,
                            "width": 400,
                            "visible": false,
                            "text": "     ",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],

                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M2",
                            "name": "Mobiletext_mobColonSymbol1",
                            "layout": true,
                            "visible": true,
                            "uimode": "mobile",
                            "type": "Text",
                            "x": 1349,
                            "y": 1048,
                            "width": 18,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M1",
                            "name": "Mobiletext_win_label",
                            "type": "Text",
                            "layout": true,
                            "visible": true,
                            "uimode": "mobile",
                            "x": 1340,
                            "y": 1050,
                            "width": 200,
                            "text": "buttonPanelText_5",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M3",
                            "name": "Mobiletext_win_value",
                            "type": "Text",
                            "layout": true,
                            "visible": true,
                            "uimode": "mobile",
                            "x": 300,
                            "y": 1050,
                            "width": 200,
                            "text": "            ",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 34,
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M5",
                            "name": "Mobiletext_mobColonSymbol2",
                            "layout": true,
                            "uimode": "mobile",
                            "type": "Text",
                            "x": 509,
                            "y": 1048,
                            "width": 18,
                            "visible": true,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "text_M4",
                            "name": "Mobiletext_balance_label",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "x": 400,
                            "y": 1050,
                            "visible": true,
                            "width": 520,
                            "text": "buttonPanelText_3",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "text_M8",
                            "name": "Mobiletext_mobColonSymbol3",
                            "layout": true,
                            "visible": true,
                            "uimode": "mobile",
                            "type": "Text",
                            "x": 981,
                            "y": 1048,
                            "width": 18,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },


                        {
                            "id": "text_M8",
                            "name": "Mobiletext_mobColonSymbol4",
                            "layout": true,
                            "visible": true,
                            "uimode": "mobile",
                            "type": "Text",
                            "x": 1655,
                            "y": 1048,
                            "width": 18,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M8",
                            "name": "Mobiletext_mobColonSymbol5",
                            "layout": true,
                            "uimode": "mobile",
                            "type": "Text",
                            "x": 512,
                            "y": 934,
                            "width": 18,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M6",
                            "name": "Mobiletext_balance_value",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "x": 418,
                            "y": 1050,
                            "visible": true,
                            "width": 206,
                            "text": "MobViewButtonPanelText2",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M7",
                            "name": "Mobiletext_bet_label",
                            "type": "Text",
                            "layout": true,
                            "visible": true,
                            "uimode": "mobile",
                            "x": 968,
                            "y": 1050,
                            "width": 250,
                            "text": "buttonPanelText_1",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M9",
                            "name": "Mobiletext_bet_value",
                            "type": "Text",
                            "layout": true,
                            "visible": true,
                            "uimode": "mobile",
                            "x": 993,
                            "y": 1050,
                            "width": 100,
                            "text": "abcdef",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fill: ['#ffffff'],

                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "BG_balance_Text_Bg_Image",
                            "name": "BG_balance_Text_Bg_Image",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "interactive": false,
                            "x": 1499,
                            "y": 929,
                            "width": 262,
                            "height": 68,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'balance.png',
                                out: 'balance.png',
                                down: 'balance.png',
                                disable: 'balance.png',
                                enable: 'balance.png',
                                hover: 'balance.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "BG_balance_Text_Bg_Image_Social",
                            "name": "BG_balance_Text_Bg_Image_Social",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "interactive": false,
                            "x": 1225,
                            "y": 929,
                            "width": 467,
                            "height": 65,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'balance_2.png',
                                out: 'balance_2.png',
                                down: 'balance_2.png',
                                disable: 'balance_2.png',
                                enable: 'balance_2.png',
                                hover: 'balance_2.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        
                        {
                            "id": "text_7",
                            "name": "text_balance_label",
                            "type": "Text",
                            "uimode": "desktop",
                            "x": 1630,
                            "y": 910,
                            "width": 290,
                            "visible": true,
                            "text": "buttonPanelText_0",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 27,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                                wordWrap: true,
                                align: 'center'
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_7",
                            "name": "text_balance_label_mobile",
                            "type": "Text",
                            "uimode": "mobile",
                            "layout": true,
                            "x": 1630,
                            "y": 910,
                            "width": 890,
                            "visible": true,
                            "text": "buttonPanelText_0",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                                wordWrap: true,
                                align: 'center'
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_8",
                            "name": "text_balance_value_desktop",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 1628,
                            "y": 964.5,
                            "width": 1200,
                            "visible": true,
                            "text": "abcd",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "text_8_mobile",
                            "name": "text_balance_value_mobile",
                            "uimode": "mobile",
                            "layout": true,
                            "type": "Text",
                            "x": 524,
                            "y": 935.5,
                            "width": 200,
                            "visible": true,
                            "text": "abcd",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 34,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "autoplay_Counter",
                            "name": "autoplay_Counter",
                            "image": "autoplay_counter.png",
                            "type": "Image",
                            "uimode": "desktop",
                            "class": "",
                            "filterTypes": [],
                            "visible": true,
                            "interactive": false,
                            "x": 909,
                            "y": 1036,
                            "width": 99,
                            "height": 46,
                        },

                        {
                            "id": "MobileSettingPanelTag",
                            "name": "MobileSettingPanel",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },

                        {
                            "id": "CanvasMobilePaytable",
                            "name": "CanvasMobilePaytable",
                            "type": "Tag",
                            "class": "",
                            child: []
                        },
                        {
                            "id": "CanvasMobileBet",
                            "name": "CanvasMobileBet",
                            "type": "Tag",
                            "class": "",
                            child: []
                        },
                        {
                            "id": "CanvasMobilePaytablePortrait",
                            "name": "CanvasMobilePaytablePortrait",
                            "type": "Tag",
                            "class": "",
                            child: []
                        },

                        {
                            "id": "CanvasAutoplayPortrait",
                            "name": "CanvasAutoplayPortrait",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                        {
                            "id": "NoInternetPopUp",
                            "name": "NoInternetPopUp",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                        {
                            "id": "SoundText",
                            "name": "SoundText",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },

                    ]
                }
            ]
        },
    ]
}