import { frameworkButtonPanel } from "../../../core/components/buttonpanel/configuration/buttonpanelconfiguration"
import { objectTypes } from "../../../core/components/buttonpanel/interface/Ibuttons";


frameworkButtonPanel.data = {
    "alwaysEnableButtonNameList": ["btn_setting"],
    "COREBUTTONPANEL": [],
    "COMPONENTS": [

        {
            "id": "GenericUIContainer",
            "name": "GenericUIContainer",
            "type": "Container",
            "class": "",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            child: [
                {
                    "id": "GenericUIComponent",
                    "name": "ButtonPanelGenericUI",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    "alwaysEnableButtonNameList": ["btn_help", "btn_sound", "btn_soundOff","btn_spinStop"],
                    child: [
                        {
                            "id": "button_Panel_Left_BottomBar",
                            "name": "button_Panel_Left_BottomBar",
                            "image": "bg_leftbar.png",
                            "type": "Image",
                            "uimode": "desktop",
                            "class": "",
                            "filterTypes": [],
                            "visible": true,
                            "interactive": false,
                            "x": 0,
                            "y": 1022,
                            "width": 934,
                            "height": 58,
                        },
                        {
                            "id": "button_Panel_Right_BottomBar",
                            "name": "button_Panel_Right_BottomBar",
                            "image": "bg_right_bar.png",
                            "type": "Image",
                            "uimode": "desktop",
                            "class": "",
                            "filterTypes": [],
                            "visible": true,
                            "interactive": false,
                            "x": 986,
                            "y": 1022,
                            "width": 934,
                            "height": 58,
                        },
                        {
                            "id": "BG_bet_Text_Bg_Image",
                            "name": "BG_bet_Text_Bg_Image",
                            "image": "bet.png",
                            "type": "Image",
                            "uimode": "desktop",
                            "class": "",
                            "filterTypes": [],
                            "visible": true,
                            "width": 226,
                            "height": 65,
                            "x": 224,
                            "y": 929,
                        },
                           {
                            "id": "BG_bet_Text_Bg_Image_Social",
                            "name": "BG_bet_Text_Bg_Image_Social",
                            "image": "bet_2.png",
                            "type": "Image",
                            "uimode": "desktop",
                            "class": "",
                            "filterTypes": [],
                            "visible": true,
                            "width": 467,
                            "height": 65,
                            "x": 224,
                            "y": 929,
                        },
                        
                        {
                            "id": "BG_coin_increment_decrement_Bg_Image",
                            "name": "BG_coin_increment_decrement_Bg_Image",
                            "image": "coin.png",
                            "type": "Image",
                            "uimode": "desktop",
                            "class": "",
                            "filterTypes": [],
                            "visible": true,
                            "interactive": false,
                            "x": 464,
                            "y": 929,
                            "width": 228,
                            "height": 66,
                        },
                        {
                            "id": "btn_spin",
                            "name": "btn_spin",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 884,
                            "y": 886,
                            "height": 156,
                            "width": 156,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'spin_up.png',
                                out: 'spin_up.png',
                                down: 'spin_down.png',
                                disable: 'spin_disable.png',
                                enable: 'spin_up.png',
                                hover: 'spin_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {
                                type: "circle",
                                x: 70,
                                y: 60,
                                r: 80,
                            },
                        },
                        {
                            "id": "Button_2",
                            "name": "btn_paytable",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 151,
                            "y": 929,
                            "height": 70,
                            "width": 70,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'paytable_up.png',
                                out: 'paytable_up.png',
                                down: 'paytable_down.png',
                                disable: 'paytable_disable.png',
                                enable: 'paytable_up.png',
                                hover: 'paytable_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_3",
                            "name": "btn_bet_increase",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 641,
                            "y": 937,
                            "height": 50,
                            "width": 40,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'plus_up.png',
                                out: 'plus_up.png',
                                down: 'plus_down.png',
                                disable: 'over_disable.png',
                                enable: 'plus_up.png',
                                hover: 'over_up.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_4",
                            "name": "btn_bet_decrease",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 474,
                            "y": 938,
                            "height": 50,
                            "width": 40,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'minus_up.png',
                                out: 'minus_up.png',
                                down: 'minus_down.png',
                                disable: 'minus_disable.png',
                                enable: 'minus_up.png',
                                hover: 'minus_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_5",
                            "name": "btn_sound",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 1795,
                            "y": 1025,
                            "height": 60,
                            "width": 60,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'sound_up.png',
                                out: 'sound_up.png',
                                down: 'sound_down.png',
                                disable: 'sound_disable.png',
                                enable: 'sound_up.png',
                                hover: 'sound_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_6",
                            "name": "btn_gameRule",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 70,
                            "y": 1025,
                            "height": 60,
                            "width": 60,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'gamerule_up.png',
                                out: 'gamerule_up.png',
                                down: 'gamerule_down.png',
                                disable: 'gamerule_disable.png',
                                enable: 'gamerule_up.png',
                                hover: 'gamerule_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                       

                        {
                            "id": "Button_7",
                            "name": "btn_autoplay_stop",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": false,
                            "x": 1032,
                            "y": 911,
                            "height": 106,
                            "width": 184,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'autoplayoff_up.png',
                                out: 'autoplayoff_up.png',
                                down: 'autoplayoff_down.png',
                                disable: 'autoplayoff_disable.png',
                                enable: 'autoplayoff_up.png',
                                hover: 'autoplayoff_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_8",
                            "name": "btn_autoplay",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 1032,
                            "y": 911,
                            "height": 103,
                            "width": 181,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'autoplay_up.png',
                                out: 'autoplay_up.png',
                                down: 'autoplay_down.png',
                                disable: 'autoplay_disable.png',
                                enable: 'autoplay_up.png',
                                hover: 'autoplay_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {
                                type: "rectangle",
                                x: 0,
                                y: 0,
                                w: 160,
                                h: 106
                            },

                        },
                        {
                            "id": "Button_9",
                            "name": "btn_home",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 10,
                            "y": 1025,
                            "height": 60,
                            "width": 60,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'home_up.png',
                                out: 'home_up.png',
                                down: 'home_down.png',
                                disable: 'home_disable.png',
                                enable: 'home_up.png',
                                hover: 'home_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_10",
                            "name": "btn_maxbet",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 707,
                            "y": 911,
                            "height": 106,
                            "width": 184,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'maxbet_up.png',
                                out: 'maxbet_up.png',
                                down: 'maxbet_down.png',
                                disable: 'maxbet_disable.png',
                                enable: 'maxbet_up.png',
                                hover: 'maxbet_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {
                                type: "rectangle",
                                x: 0,
                                y: 0,
                                w: 160,
                                h: 106
                            }
                        },
                        {
                            "id": "Button_11",
                            "name": "btn_setting",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 1855,
                            "y": 1025,
                            "height": 60,
                            "width": 60,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'setting_up.png',
                                out: 'setting_up.png',
                                down: 'setting_down.png',
                                disable: 'setting_disable.png',
                                enable: 'setting_up.png',
                                hover: 'setting_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {},

                        },
                        {
                            "id": "Button_12",
                            "name": "btn_soundOff",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 1795,
                            "y": 1025,
                            "height": 60,
                            "width": 60,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'soundoff_up.png',
                                out: 'soundoff_up.png',
                                down: 'soundoff_down.png',
                                disable: 'soundoff_disable.png',
                                enable: 'soundoff_up.png',
                                hover: 'soundoff_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_12",
                            "name": "btn_sounddisable",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 1795,
                            "y": 1025,
                            "height": 60,
                            "width": 60,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up:  'soundoff_disable.png',
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_14",
                            "name": "btn_responsibleGammingIcon",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 80,
                            "y": 930,
                            "height": 60,
                            "width": 60,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'blankImage',
                                out: '',
                                down: '',
                                disable: '',
                                enable: '',
                                hover: ''
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {},
                        },

                        {
                            "id": "Button_15",
                            "name": "btn_spinStop",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "layout": false,
                            "x": 940,
                            "y": 945,
                            "height": 42,
                            "width": 42,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'slam_down.png',
                                out: 'slam_down.png',
                                down: 'slam_down.png',
                                disable: 'slam_disable.png',
                                enable: 'slam.png',
                                hover: 'slam_down.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },

                        //MOBILE VIEW BUTTONS----------------------------------------

                        {
                            "id": "Button_M14",
                            "name": "btn_responsibleGammingIcon",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "layout": true,
                            "uimode": "mobile",
                            "interactive": true,
                            "width": 98,
                            "height": 100,
                            "x": 0,
                            "y": 0,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'blankImage',
                                out: '',
                                down: '',
                                disable: '',
                                enable: '',
                                hover: ''
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },

                        {
                            "id": "Button_M1",
                            "name": "btn_autoplay2",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "layout": true,
                            "uimode": "mobile",
                            "x": 1612,
                            "y": 252,
                            "height": 157,
                            "width": 268,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'mobileautoplay_up.png',
                                out: 'mobileautoplay_up.png',
                                down: 'mobileautoplay_down.png',
                                disable: 'mobileautoplay_disable.png',
                                enable: 'mobileautoplay_up.png',
                                hover: 'mobileautoplay_up.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_M2",
                            "name": "btn_spin",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "layout": true,
                            "uimode": "mobile",
                            "x": 1600,
                            "y": 322,
                            "height": 300,
                            "width": 300,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'mobilespin_up.png',
                                out: 'mobilespin_up.png',
                                down: 'mobilespin_down.png',
                                disable: 'mobilespin_disable.png',
                                enable: 'mobilespin_up.png',
                                hover: 'mobilespin_up.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },

                        {
                            "id": "Button_M3",
                            "name": "btn_autoplay_stop",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "layout": true,
                            "uimode": "mobile",
                            "x": 1660,
                            "y": 667,
                            "height": 130,
                            "width": 130,
                            "anchor": [0.5, 0.5],
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'mobilespin_disable.png',
                                out: 'mobilespin_disable.png',
                                down: 'mobilespin_disable.png',
                                disable: 'mobilespin_disable.png',
                                enable: 'mobilespin_disable.png',
                                hover: 'mobilespin_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },

                        {
                            "id": "Button_M4",
                            "name": "btn_autoplay",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "layout": true,
                            "uimode": "mobile",
                            "interactive": true,
                            "x": 1760,
                            "y": 890,
                            "height": 81,
                            "width": 88,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'mobilehamburger_up.png',
                                out: 'mobilehamburger_up.png',
                                down: 'mobilehamburger_up.png',
                                disable: 'mobilehamburger_disable.png',
                                enable: 'mobilehamburger_up.png',
                                hover: 'mobilehamburger_up.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_M5",
                            "name": "btn_home",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "layout": true,
                            "uimode": "mobile",
                            "interactive": true,
                            "x": 80,
                            "y": 890,
                            "height": 94,
                            "width": 102,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'mobilehome_up.png',
                                out: 'mobilehome_up.png',
                                down: 'mobilehome_up.png',
                                disable: 'mobilehome_disable.png',
                                enable: 'mobilehome_up.png',
                                hover: 'mobilehome_up.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },

                        {
                            "id": "text_9",
                            "name": "text_maxBet_label1",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 800,
                            "y": 950,
                            "width": 110,
                            "visible": true,
                            "text": "buttonPanelText_9",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 25,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_13",
                            "name": "text_maxBet_label1_grey",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 800,
                            "y": 950,
                            "width": 110,
                            "visible": false,
                            "text": "buttonPanelText_9",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 25,
                                fontWeight: 'bold',
                                fill: ['#676262'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_10",
                            "name": "text_maxBet_label2",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 800,
                            "y": 980,
                            "width": 110,
                            "visible": true,
                            "text": "buttonPanelText_10",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 25,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_14",
                            "name": "text_maxBet_label2_grey",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 800,
                            "y": 980,
                            "width": 110,
                            "visible": false,
                            "text": "buttonPanelText_10",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 25,
                                fontWeight: 'bold',
                                fill: ['#676262'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "Button_M15",
                            "name": "btn_spinStop",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "layout": true,
                            "uimode": "mobile",
                            "interactive": true,
                            "x": 1700,
                            "y": 420,
                            "height": 100,
                            "width": 100,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'slam_down.png',
                                out: 'slam_down.png',
                                down: 'slam_down.png',
                                disable: 'slam_disable.png',
                                enable: 'slam.png',
                                hover: 'slam_down.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "text_11",
                            "name": "text_AUTOPLAY_label1",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 1126,
                            "y": 961,
                            "width": 105,
                            "text": "autoplayText_24",
                            "scaleToFit": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 25,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                                wordWrap: true,
                                wordWrapWidth: 80,
                                align: 'center',
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_15",
                            "name": "text_AUTOPLAY_label1_grey",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 1126,
                            "y": 961,
                            "width": 105,
                            "text": "autoplayText_24",
                            "scaleToFit": true,
                            "visible": false,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 25,
                                fontWeight: 'bold',
                                fill: ['#676262'],
                                wordWrap: true,
                                wordWrapWidth: 80,
                                align: 'center',
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "text_24",
                            "name": "Text_COUNT_AP",
                            "type": "Text",
                            "uimode": "desktop",
                            "x": 963,
                            "y": 1062,
                            "text": "",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            width: 64,
                            "scaleToFit": true,
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 30,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                                align: "center",
                                dropShadow: true,
                                dropShadowColor: '#000000',
                                dropShadowBlur: 4,
                                dropShadowAngle: Math.PI / 6,
                                dropShadowDistance: 6,
                                wordWrap: true,
                                wordWrapWidth: 440
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_1",
                            "name": "text_bet_label_button",
                            "type": "Text",
                            "uimode": "desktop",
                            "x": 340,
                            "y": 910,
                            "visible": true,
                            "width": 180,
                            "text": "buttonPanelText_1",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 27,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_2",
                            "name": "text_bet_value1",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 337,
                            "y": 961.5,
                            "width": 160,
                            "visible": true,
                            "text": "buttonPanelText_2",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fontWeight: 'bold',
                                fill: ['#ffffff', '#ffffff', '#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_1",
                            "name": "text_bet_label_button_mobile",
                            "type": "Text",
                            "uimode": "mobile",
                            "layout": true,
                            "x": 340,
                            "y": 910,
                            "visible": true,
                            "width": 500,
                            "text": "buttonPanelText_1",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_2",
                            "name": "text_bet_value1_mobile",
                            "uimode": "mobile",
                            "layout": true,
                            "type": "Text",
                            "x": 337,
                            "y": 961.5,
                            "width": 100,
                            "visible": true,
                            "text": "buttonPanelText_2",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 34,
                                fontWeight: 'bold',
                                fill: ['#ffffff', '#ffffff', '#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_3",
                            "name": "text_coin_value_LABEL",
                            "type": "Text",
                            "uimode": "desktop",
                            "x": 580,
                            "y": 910,
                            "width": 300,
                            "visible": true,
                            "text": "buttonPanelText_7",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 27,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                                wordWrap: true,
                                wordWrapWidth: 290,
                                align: 'center'
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "text_4",
                            "name": "text_coinValue_value",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 580,
                            "y": 963.5,
                            "width": 150,
                            "visible": true,
                            "text": "67",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },


                        //Mobile View Text-----------------------------------------
                        {
                            "id": "auto_play_text_Image",
                            "name": "auto_play_text_Image",
                            "image": 'mobilespin_disable.png',
                            "type": "Image",
                            "uimode": "mobile",
                            "class": "",
                            "filterTypes": [],
                            "visible": false,
                            "interactive": false,
                            "anchor": [0.5, 0.5],
                            "x": 1848,
                            "y": 667,
                            "width": 130,
                            "height": 130,
                        },

                        {
                            "id": "text_M10",
                            "name": "Text_COUNT_AP",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "x": 1848,
                            "y": 667,
                            "text": "",
                            "width": 70,
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "scaleToFit": false,
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 52,
                                fontWeight: 'bold',
                                fill: ['#FFFFFF'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "auto_play_Stop_Image_text",
                            "name": "auto_play_Stop_Image_text",
                            "uimode": "mobile",
                            "type": "Text",
                            "x": 1660,
                            "y": 667,
                            "width": 100,
                            "visible": false,
                            "text": "AUTO OFF",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 30,
                                fontWeight: 'bold',
                                align:'center',
                                fill: ['#ffffff'],
                                wordWrap: true,
                                wordWrapWidth: 50,
                            },
                        },
                    ]
                }
            ]

        },

    ],
}