import { frameworkPlayerMessage } from "../../../core/components/playerMessage/configuration/playerMessageconfiguration"
import React from "react";


frameworkPlayerMessage.data = {
    "leftContainerInterval": 4000,
    "rightContainerInterval": 2000,
    "COMPONENTS": [
        {
            "id": "BMPlayerMessageContainer",
            "name": "BMPlayerMessageContainer",
            "type": "Container",
            "class": "",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "parentLayer": "baseLayer",
            child: [
                {
                    "id": "BMPlayerMessageComponent",
                    "name": "GofPlayerMessage",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            id: "container_leftInfo",
                            "name": "leftInfoContainer",
                            "type": "Container",
                            "class": "",
                            "visible": true,
                            "uimode": "desktop",
                            "x": 0,
                            "y": 1022,
                            "width": 934,
                            "height": 58,
                            "filterTypes": [],
                            child: [
                                {
                                    id: "container_leftInfo1",
                                    "name": "leftInfoContainer1",
                                    "type": "Container",
                                    "class": "",
                                    "visible": true,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [
                                        {
                                            "id": "text_Good_Luck",
                                            "name": "good_Luck_Text",
                                            "uimode": "desktop",
                                            "type": "Text",
                                            "x": 520,
                                            "y": 32,
                                            "width": 500,
                                            "visible": false,
                                            "text": "buttonPanelText_18",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                        {
                                            "id": "textOfContainer1_1",
                                            "name": "text_bet_label",
                                            "type": "Text",
                                            "x": 295,
                                            "y": 32,
                                            "width": 180,
                                            "visible": true,
                                            "text": "buttonPanelText_1",
                                            "scaleToFit": true,
                                            "anchor": [1, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "MaxWinOdd_text",
                                            "name": "MaxWinOdd_text",
                                            "type": "Container",
                                            "class": "",
                                            "visible": true,
                                            "uimode": "desktop",
                                            "x": 0,
                                            "y": 0,
                                            "width": 1500,
                                            "height": 250,
                                            "filterTypes": [],
                                            child: [
                                                {
                                                    "id": "setMaxWinOdd_text",
                                                    "name": "setMaxWinOdd_text",
                                                    "type": "Text",
                                                    "uimode": "desktop",
                                                    "x": 255,
                                                    "y": -10,
                                                    "width": 1500,
                                                    "visible": true,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [1, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontWeight: 'bold',
                                                        fontSize: 24,
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },
                                                {
                                                    "id": "setMaxWinOdd",
                                                    "name": "setMaxWinOdd",
                                                    "type": "Text",
                                                    "uimode": "desktop",
                                                    "x": 256,
                                                    "y": -10,
                                                    "width": 500,
                                                    "visible": true,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [0, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontWeight: 'bold',
                                                        fontSize: 24,
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },
                                            ],
                                        },
                                        {
                                            "id": "game_clock",
                                            "name": "game_clock",
                                            "uimode": "desktop",
                                            "type": "Text",
                                            "x": 70,
                                            "y": -982,
                                            "width": 155,
                                            "visible": false,
                                            "text": "10:50",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_rtp_text",
                                            "name": "game_rtp_text",
                                            "type": "Text",
                                            "x": 1769,
                                            "y": -10,
                                            "width": 100,
                                            "visible": true,
                                            "text": "gameGuideText2_7",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 24,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_rtp",
                                            "name": "game_rtp",
                                            "type": "Text",
                                            "x": 1869,
                                            "y": -10,
                                            "width": 100,
                                            "visible": false,
                                            "text": "0.00",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 24,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "textOfContainer1_2",
                                            "name": "text_colonSymbol1",
                                            "type": "Text",
                                            "x": 305,
                                            "y": 30,
                                            "width": 12,
                                            "visible": true,
                                            "text": "buttonPanelText_13",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "textOfContainer1_3",
                                            "name": "text_bet_value",
                                            "type": "Text",
                                            "x": 315,
                                            "y": 32,
                                            "width": 100,
                                            "visible": true,
                                            "text": "abcdef",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                        {
                                            "id": "textOfContainer1_4",
                                            "name": "text_Coin_value_label",
                                            "type": "Text",
                                            "x": 752,
                                            "y": 32,
                                            "width": 370,
                                            "visible": true,
                                            "text": "buttonPanelText_7",
                                            "scaleToFit": true,
                                            "anchor": [1, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                      
                                        {
                                            "id": "textOfContainer1_5",
                                            "name": "text_colonSymbol2",
                                            "type": "Text",
                                            "x": 761,
                                            "y": 30,
                                            "width": 12,
                                            "visible": true,
                                            "text": "buttonPanelText_13",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "textOfContainer1_6",
                                            "name": "text_Coin_value_value",
                                            "type": "Text",
                                            "x": 770,
                                            "y": 32,
                                            "width": 1000,
                                            "visible": true,
                                            "text": "abcde",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },

                                {
                                    id: "container_leftInfo2",
                                    "name": "leftInfoContainer2",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": false,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer2_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is message to display, for left Container----2",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },

                                {
                                    id: "container_leftInfo3",
                                    "name": "leftInfoContainer3",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer3_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is Game Rules button and showing in left Container----3",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },

                                {
                                    id: "container_leftInfo4",
                                    "name": "leftInfoContainer4",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----4",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },

                                {
                                    id: "container_leftInfo5",
                                    "name": "leftInfoContainer5",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": false,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----5",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },
                                {
                                    id: "container_leftInfo6",
                                    "name": "leftInfoContainer6",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----6",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },
                                {
                                    id: "container_leftInfo7",
                                    "name": "leftInfoContainer7",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----7",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },
                                {
                                    id: "container_leftInfo8",
                                    "name": "leftInfoContainer8",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": false,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$---8",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },
                                {
                                    id: "container_leftInfo9",
                                    "name": "leftInfoContainer9",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": false,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----9",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },
                                {
                                    id: "container_leftInfo10",
                                    "name": "leftInfoContainer10",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----10",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },

                            ]

                        },
                        {
                            id: "container_leftInfo",
                            "name": "leftInfoContainer",
                            "type": "Container",
                            "class": "",
                            "visible": true,
                            "layout": true,
                            "uimode": "mobile",
                            "x": 0,
                            "y": 1022,
                            "width": 934,
                            "height": 58,
                            "filterTypes": [],
                            child: [
                                {
                                    id: "container_leftInfo1",
                                    "name": "leftInfoContainer1",
                                    "type": "Container",
                                    "class": "",
                                    "visible": true,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [
                                        {
                                            "id": "textOfContainer2_1",
                                            "name": "text_Win_label_mobile",
                                            "type": "Text",
                                            "x": 155,
                                            "y": 32,
                                            "width": 300,
                                            "visible": true,
                                            "text": "buttonPanelText_5",
                                            "scaleToFit": true,
                                            "anchor": [1, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 32,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "textOfContainer2_2",
                                            "name": "text_colonSymbol3_mobile",
                                            "type": "Text",
                                            "x": 167,
                                            "y": 30,
                                            "width": 12,
                                            "visible": true,
                                            "text": "buttonPanelText_13",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 32,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "textOfContainer2_3",
                                            "name": "text_Win_value_mobile",
                                            "type": "Text",
                                            "x": 175,
                                            "y": 34,
                                            "width": 200,
                                            "visible": false,
                                            "text": "abcdefg",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 34,
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_clock_m",
                                            "name": "game_clock_m",
                                            "type": "Text",
                                            "x": 96,
                                            "y": -972,
                                            "width": 350,
                                            "visible": false,
                                            "text": "10:50",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 38,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_clock_m",
                                            "name": "game_clock_m_portrait",
                                            "type": "Text",
                                            "x": 300,
                                            "y": -972,
                                            "width": 350,
                                            "visible": false,
                                            "text": "10:50",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 38,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_rtp_m_text",
                                            "name": "game_rtp_m_text",
                                            "type": "Text",
                                            "x": 1725,
                                            "y": -28,
                                            "width": 400,
                                            "visible": false,
                                            "text": "gameGuideText2_7",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 28,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_rtp_m",
                                            "name": "game_rtp_m",
                                            "type": "Text",
                                            "x": 1840,
                                            "y": -28,
                                            "width": 400,
                                            "visible": false,
                                            "text": "0.00",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 28,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                        {
                                            "id": "game_rtp_m_text_portrait",
                                            "name": "game_rtp_m_text_portrait",
                                            "type": "Text",
                                            "x": 1115,
                                            "y": 647,
                                            "width": 400,
                                            "visible": false,
                                            "text": "gameGuideText2_7",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 28,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_rtp_m_portrait",
                                            "name": "game_rtp_m_portrait",
                                            "type": "Text",
                                            "x": 1233,
                                            "y": 647,
                                            "width": 400,
                                            "visible": false,
                                            "text": "0.00",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 28,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "MaxWinOdd_text_landscape",
                                            "name": "MaxWinOdd_text_landscape",
                                            "type": "Container",
                                            "class": "",
                                            "visible": true,
                                            "uimode": "desktop",
                                            "x": -277,
                                            "y": 3,
                                            "width": 1500,
                                            "height": 250,
                                            "filterTypes": [],
                                            child: [
                                                {
                                                    "id": "setMaxWinOdd_m",
                                                    "name": "setMaxWinOdd_m",
                                                    "type": "Text",
                                                    "x": 576,
                                                    "y": -29,
                                                    "width": 1500,
                                                    "visible": false,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [1, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontSize: 28,
                                                        fontStyle: 'bold',
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },
                                                {
                                                    "id": "setMaxWinOdd_m2",
                                                    "name": "setMaxWinOdd_m2",
                                                    "type": "Text",
                                                    "x": 578,
                                                    "y": -28,
                                                    "width": 1500,
                                                    "visible": false,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [0, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontStyle: 'bold',
                                                        fontSize: 28,
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },
                                            ],
                                        },

                                        {
                                            "id": "MaxWinOdd_text_portrait",
                                            "name": "MaxWinOdd_text_portrait",
                                            "type": "Container",
                                            "class": "",
                                            "visible": true,
                                            "uimode": "desktop",
                                            "x": 0,
                                            "y": 0,
                                            "width": 1500,
                                            "height": 250,
                                            "filterTypes": [],
                                            child: [
                                                {
                                                    "id": "setMaxWinOdd_portrait",
                                                    "name": "setMaxWinOdd_portrait",
                                                    "type": "Text",
                                                    "x": 538,
                                                    "y": 645,
                                                    "width": 1500,
                                                    "visible": false,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [1, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontSize: 28,
                                                        fontStyle: 'bold',
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },

                                                {
                                                    "id": "setMaxWinOdd_m2_portrait",
                                                    "name": "setMaxWinOdd_m2_portrait",
                                                    "type": "Text",
                                                    "x": 539,
                                                    "y": 645,
                                                    "width": 1500,
                                                    "visible": false,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [0, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontStyle: 'bold',
                                                        fontSize: 28,
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },
                                            ]
                                        },
                                    ]

                                },

                            ]

                        },
                        {
                            "name": "baseGameBlackScreen",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "visible": false,
                            "alpha": 1,
                            "color": "0x000000",
                            "x": 0,
                            "y": 0,
                            "width": 1920,
                            "height": 1080,
                        },
                        {
                            "name": "baseGameBlackScreenPortrait",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "visible": false,
                            "alpha": 1,
                            "color": "0x000000",
                            "x": 0,
                            "y": 0,
                            "width": 1080,
                            "height": 1920,
                        },

                        {
                            id: "container_rightInfo",
                            "name": "rightInfoContainer",
                            "type": "Container",
                            "class": "",
                            "visible": true,
                            "uimode": "desktop",
                            "x": 986,
                            "y": 1022,
                            "width": 934,
                            "height": 58,
                            "filterTypes": [],
                            child: [
                                {
                                    id: "container_rightInfo1",
                                    "name": "rightInfoContainer1",
                                    "type": "Container",
                                    "class": "",
                                    "visible": true,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [
                                        {
                                            "id": "textOfContainer2_1",
                                            "name": "text_Win_label_desktop",
                                            "type": "Text",
                                            "x": 190,
                                            "y": 32,
                                            "width": 210,
                                            "visible": true,
                                            "text": "buttonPanelText_5",
                                            "scaleToFit": true,
                                            "anchor": [1, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "textOfContainer2_2",
                                            "name": "text_colonSymbol3_desktop",
                                            "type": "Text",
                                            "x": 195,
                                            "y": 30,
                                            "width": 12,
                                            "visible": true,
                                            "text": "buttonPanelText_13",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "textOfContainer2_3",
                                            "name": "text_Win_value_desktop",
                                            "type": "Text",
                                            "x": 205,
                                            "y": 32,
                                            "width": 1000,
                                            "visible": false,
                                            "text": "abcdefg",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                        {
                                            "id": "textOfContainer2_4",
                                            "name": "text_Balance_label",
                                            "type": "Text",
                                            "x": 590,
                                            "y": 32,
                                            "width": 310,
                                            "visible": true,
                                            "text": "buttonPanelText_3",
                                            "scaleToFit": true,
                                            "anchor": [1, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "textOfContainer2_5",
                                            "name": "text_colonSymbol4",
                                            "type": "Text",
                                            "x": 598,
                                            "y": 30,
                                            "width": 10,
                                            "visible": true,
                                            "text": "buttonPanelText_13",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "textOfContainer2_6",
                                            "name": "text_Balance_value_withSign",
                                            "type": "Text",
                                            "x": 607,
                                            "y": 32,
                                            "width": 200,
                                            "visible": true,
                                            "text": "buttonPanelText_16",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 26,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },

                                {
                                    id: "container_rightInfo2",
                                    "name": "rightInfoContainer2",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": false,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [
                                        {
                                            "id": "textOfContainer2_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 420,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is message to display, for right Container2",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },

                                {
                                    id: "container_rightInfo3",
                                    "name": "rightInfoContainer3",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer3_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is Game Rules button and showing in right Container3",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },

                                {
                                    id: "container_rightInfo4",
                                    "name": "rightInfoContainer4",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is ******************************************4",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },

                                {
                                    id: "container_leftInfo4",
                                    "name": "leftInfoContainer4",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----45",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },

                                {
                                    id: "container_leftInfo5",
                                    "name": "leftInfoContainer5",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": false,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----5",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },
                                {
                                    id: "container_leftInfo6",
                                    "name": "leftInfoContainer6",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----6",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },
                                {
                                    id: "container_leftInfo7",
                                    "name": "leftInfoContainer7",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----7",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {


                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },
                                {
                                    id: "container_leftInfo8",
                                    "name": "leftInfoContainer8",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": false,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$---8",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },
                                {
                                    id: "container_leftInfo9",
                                    "name": "leftInfoContainer9",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": false,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----9",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },
                                {
                                    id: "container_leftInfo10",
                                    "name": "leftInfoContainer10",
                                    "type": "Container",
                                    "class": "",
                                    "visible": false,
                                    "messageInLoop": false,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [

                                        {
                                            "id": "textOfContainer4_1",
                                            "name": "text_Message",
                                            "type": "Text",
                                            "x": 500,
                                            "y": 30,
                                            "width": 400,
                                            "visible": true,
                                            "text": "hello! this is $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$----10",
                                            "scaleToFit": false,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },

                                    ]

                                },


                            ]

                        },

                    ]

                },


            ]
        }


    ]

}