import { frameworkLayouts } from "./../../../core/components/layouts/configuration/layoutsconfiguration"


frameworkLayouts.data = {
    layouts: [
        {
            "name": "mobile_settingHeading",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 940,
            "y": 500,
        },
        {
            "name": "mobile_settingHeading",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 980,
            "y": 700,
        },
        {
            "name": "btn_responsibleGammingIcon",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 230,
            "y": 894,

        },
        {
            "name": "btn_responsibleGammingIcon",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 222,
            "y": 1815,
        },

        {
            "name": "realityCheckContainer_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 400,
        },
        {
            "name": "realityCheckContainer_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": -480,
            "y": 690,
        },
        {
            "name": "noInternetPopUpContainerMobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },
        {
            "name": "noInternetPopUpContainerMobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": -480,
            "y": 250,
        },
        {
            "name": "autoplayContent",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 200,
            "y": -150,
        },
        {
            "name": "autoplayContent",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },
        {
            "name": "leftInfoContainer",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 1022,
        },
        {
            "name": "leftInfoContainer",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": -231,
            "y": 1052,

        },
        //****************************************************************************** //

        {
            "name": "bottomSpritLineMobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 443,
        },
        {
            "name": "bottomSpritLineMobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 600,
        },
        {
            "name": "btn_spinStop",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1700,
            "y": 420,
        },
        {
            "name": "btn_spinStop",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 489,
            "y": 1349,
        },
        
        {
            "name": "mobile_turboSpinText",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1030,
            "y": 746,
        },
        {
            "name": "mobile_turboSpinText",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 955,
            "y": 1060,
        },
        {
            "name": "mobile_turboSpinRadioButtonOff",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 534,
            "y": 758,
        },
        {
            "name": "mobile_turboSpinRadioButtonOff",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 534,
            "y": 1060,
        },
        {
            "name": "mobile_turboSpinRadioButtonOn",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 530,
            "y": 758,
        },
        {
            "name": "mobile_turboSpinRadioButtonOn",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 530,
            "y": 1060,
        },
        {
            "name": "showIntroScreenRadioButtonMobileOn",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 460,
            "y": 657,
        },
        {
            "name": "showIntroScreenRadioButtonMobileOn",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 460,
            "y": 944,
        },
        {
            "name": "musicRadioButtonMobileOn",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 536,
            "y": 603,
        },
        {
            "name": "musicRadioButtonMobileOn",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 535,
            "y": 877,
        },
     
        {
            "name": "musicRadioButtonMobileOff",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 536,
            "y": 603,
        },
        {
            "name": "musicRadioButtonMobileOff",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 535,
            "y": 877,
        },
    
        {
            "name": "showIntroScreenRadioButtonMobileOff",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 460,
            "y": 657,
        },
        {
            "name": "showIntroScreenRadioButtonMobileOff",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 460,
            "y": 944,
        },
        {
            "name": "showIntroScreenTextMobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1030,
            "y": 676,
        },
        {
            "name": "showIntroScreenTextMobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 955,
            "y": 959,
        },
        {
            "name": "musicTextMobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1030,
            "y": 606,
        },
        {
            "name": "musicTextMobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 955,
            "y": 864,
        },
  

        //****************************************************************************** //
        {
            "name": "mobileSettingPanelBottomSpriteLineBar1",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 400,
            "y": 880,
        },
        {
            "name": "mobileSettingPanelBottomSpriteLineBar1",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 195,
            "y": 1780,
        },
        {
            "name": "mobileSettingPanelBottomSpriteLineBar2",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 780,
            "y": 880,
        },
        {
            "name": "mobileSettingPanelBottomSpriteLineBar2",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 430,
            "y": 1780,
        },
        {
            "name": "mobileSettingPanelBottomSpriteLineBar3",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1120,
            "y": 880,
        },
        {
            "name": "mobileSettingPanelBottomSpriteLineBar3",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 650,
            "y": 1780,
        },
        {
            "name": "mobileSettingPanelBottomSpriteLineBar4",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1500,
            "y": 880,
        },
        {
            "name": "mobileSettingPanelBottomSpriteLineBar4",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 870,
            "y": 1780,
        },
        {
            "name": "autoplayHeading_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 970,
            "y": 91,
        },
        {
            "name": "autoplayHeading_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 555,
            "y": 91,
        },
        {
            "name": "betHeading_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 970,
            "y": 91,
        },
        {
            "name": "betHeading_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 555,
            "y": 91,
        },
        {
            "name": "GameGuideHeading_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 970,
            "y": 91,
        },
        {
            "name": "GameGuideHeading_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 555,
            "y": 91,
        },
        {
            "name": "payTableHeading_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 970,
            "y": 91,
        },
        {
            "name": "payTableHeading_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 555,
            "y": 91,
        },

        {
            "name": "mobileSettingPanelTopSprite",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },
        {
            "name": "mobileSettingPanelTopSprite",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },
        {
            "name": "mobileSettingPanelTopSpriteLine",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 155,
        },
        {
            "name": "mobileSettingPanelTopSpriteLine",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 191,
        },
        {
            "name": "mobileSettingPanelBottomSprite",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 958,
            "y": 937,
        },
        {
            "name": "mobileSettingPanelBottomSprite",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 126,
            "y": 1848,
        },

        {
            "name": "mobileSettingPanelBg",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },
        {
            "name": "mobileSettingPanelBg",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },
        {
            "name": "image_basegame-bg1",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },
        {
            "name": "image_cloud_a_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": -46,
            "y": 0
        },
        {

            "name": "image_cloud_b_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1065,
            "y": 0

        },
        {
            "name": "image_basegameSky-bg_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },

        {
            "name": "image_freegame-fg1",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "x": 0,
            "y": 0,
        },
        {
            "name": "image_freegameTop-fg_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "x": 0,
            "y": 0,

        },
        {
            "name": "mobileViewBottomBArImage1",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 872
        },
        {
            "name": "mobileViewBottomBArImage1",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 1790,
        },

        {
            "name": "mobileViewBottomBArImage2",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 1010
        },
        {
            "name": "mobileViewBottomBArImage2",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 1720,
        },
        {
            "name": "betContent",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 37,
            "y": 40,
        },
        {
            "name": "betContent",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": -202,
            "y": 215,
        },
        {
            "name": "Bet_Container1Mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 0,
            "y": 0,
        },
        {
            "name": "Bet_Container1Mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": -493,
            "y": 76,
        },

        {

            "name": "btn_home",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 80,
            "y": 890,

        },
        {
            "name": "btn_home",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 80,
            "y": 1820,
        },

        {
            "id": "Button_M4",
            "name": "btn_autoplay",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1760,
            "y": 890,
        },
        {
            "id": "Button_M4",
            "name": "btn_autoplay",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 920,
            "y": 1820,
        },
        {
            "name": "btn_spin",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1600,
            "y": 322,
        },
        {
            "name": "btn_spin",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 390,
            "y": 1250,
        },

        {
            "name": "image_commongame-potrait-bg",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 540,
            "y": 960,
        },
        {

            "name": "image_commongame-potrait-bg",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 540,
            "y": 960,

        },

        {
            "name": "BG_gameLogo_Anim",
            "uiMode": "desktop",
            "screenMode": "",
            "handMode": "right",
            "visible": true,
            "x": 138.5,
            "y": 186.5,
        },
        {
            "name": "BG_gameLogo_Anim",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 138.5,
            "y": 186.5,
        },
        {
            "name": "BG_gameLogo_Anim",
            "uiMode": "mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "visible": true,
            "x": 528.5,
            "y": 156.5,
        },


        {
            "name": "BG_frame_Image",
            "uiMode": "desktop",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": true,
            "x": 959.5,
            "y": 502.5
        },
        {

            "name": "BG_frame_Image",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 959.5,
            "y": 502.5

        },

        {
            "name": "BG_frame_Image",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 0,
            "y": 0,
        },
        {
            "name": "BG_frame_Image",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 540,
            "y": 960,
        },

        {

            "name": "BG_leftTorchFlame_Anim_mobile",
            "uiMode": "mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": true,
            "x": 135,
            "y": 715,
        },
        {

            "name": "BG_rightTorchFlame_Anim_mobile",
            "uiMode": "mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": true,
            "x": 1778,
            "y": 715,
        },
        {

            "name": "BG_gameLogo_Anim_mobile",
            "uiMode": "mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": true,
            "x": 128.5,
            "y": 186.5,
        }, {

            "name": "FG_gameLogo_Anim_mobile",
            "uiMode": "mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": true,
            "x": 118.5,
            "y": 186.5,
        }, {

            "name": "FG_gameLogo_Anim_mobile",
            "uiMode": "mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "visible": true,
            "x": 538.5,
            "y": 176.5,
        },
        {

            "name": "BG_gameLogo_Anim_mobile",
            "uiMode": "mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "visible": true,
            "x": 538.5,
            "y": 176.5,
        },
        {

            "name": "BG_frame_Image_Mobile",
            "uiMode": "mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": true,
            "x": 959.5,
            "y": 542.5
        },
        {

            "name": "BG_frame_Image_Mobile",
            "uiMode": "mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "visible": true,
            "x": 538,
            "y": 792,
        },
        {

            "name": "BG_reelOfFrame_Image_Mobile",
            "uiMode": "mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": true,
            "x": 959.5,
            "y": 502.5
        },
        {

            "name": "BG_reelOfFrame_Image_Mobile",
            "uiMode": "mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "visible": true,
            "x": 545,
            "y": 772,
        }, {

            "name": "frameReel_FG_Image_Mob",
            "uiMode": "mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": true,
            "x": 295.5,
            "y": 76
        },
        {

            "name": "frameReel_FG_Image_Mob",
            "uiMode": "mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "visible": true,
            "x": -42,
            "y": 380,
        },
        {

            "name": "frame_FG_Image_Mob",
            "uiMode": "mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": true,
            "x": -2.5,
            "y": -3
        },
        {

            "name": "frame_FG_Image_Mob",
            "uiMode": "mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "visible": true,
            "x": -309,
            "y": 319,
        },
        {

            "name": "btn_homeFG",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,

            "x": 80,
            "y": 890,

        },
        {

            "name": "btn_homeFG",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,

            "x": 60,
            "y": 1750,

        },
       
        {
            "name": "btn_autoplay",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1760,
            "y": 890,

        },
        {
            "name": "btn_autoplay",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 920,
            "y": 1820,

        },
        {
            "name": "btn_autoplayFG",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1760,
            "y": 890,

        },
        {
            "name": "btn_autoplayFG",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 920,
            "y": 1750,

        },

        {

            "name": "mobileViewBottomBArImage1FG",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 860

        },
        {

            "name": "mobileViewBottomBArImage1FG",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 1710,

        },
        {

            "name": "mobileViewBottomBArImage2FG",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 1010

        },
        {

            "name": "mobileViewBottomBArImage2FG",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 1850,

        },

        {
            "name": "text_FreeGame_OF_label_mobileFG",
            "uiMode": "mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": false,
            "x": 810,
            "y": 940,
        },
        {
            "name": "text_FreeGame_OF_label_mobileFG",
            "uiMode": "mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "visible": false,
            "x": 547,
            "y": 1806,
        },

        {
            "name": "text_FreeGame_value2_mobileFG",
            "uiMode": "mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "visible": false,
            "x": 1090,
            "y": 940,
        },
        {
            "name": "text_FreeGame_value2_mobileFG",
            "uiMode": "mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "visible": false,
            "x": 656,
            "y": 1806,
        },

        {
            "name": "mobileViewBottomBArLineImageFG_1",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 270,
            "y": 872
        },
        {
            "name": "mobileViewBottomBArLineImageFG_1",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 210,
            "y": 1736,
        },
        {
            "name": "mobileViewBottomBArLineImageFG_2",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 870,
            "y": 1736,
        },

        {
            "name": "mobileViewBottomBArLineImageFG_2",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 940,
            "y": 872
        },

        {
            "name": "FG_leftTorchFlame_Anim_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 134,
            "y": 684,
        },
        {
            "name": "FG_rightTorchFlame_Anim_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1776,
            "y": 684,
        },
        {
            "name": "FG_Left_DrippingLava0_Anim_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 293,
            "y": 338,
        },
        {
            "name": "FG_Right_DrippingLava0_Anim_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "anchor": [-1, 1],
            "x": 1580,
            "y": 372,
        },
        {
            "name": "FG_Left_DrippingLava1_Anim_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 299,
            "y": 461,
        },
        {
            "name": "FG_Right_DrippingLava1_Anim_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1621,
            "y": 461,
        },
   
        {
            "name": "FG_smoke_Anim_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1,
            "y": 1150,
        },

        {
            "name": "Mobiletext_win_label_FG",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 449,
            "y": 1642,
        }, 
         {
            "name": "Mobiletext_win_value_FG",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "x": 630,
            "y": 1640,
        },

        {
            "name": "FG_bugFLies_Anim_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },

        {
            "name": "BG_manywaysText_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 950,
            "y": -152,
        },
        {
            "name": "BG_manywaysText_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 550,
            "y": 158,
        },

        {
            "name": "FG_manywaysText_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 960,
            "y": -154,
        },
        {
            "name": "FG_manywaysText_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 550,
            "y": 162,
        },

        {
            "name": "BG_textManyWays_Image_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1022,
            "y": 44,
        },
        {
            "name": "BG_textManyWays_Image_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 598,
            "y": 353,
        },

        {
            "name": "FG_textManyWays_Image_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1032,
            "y": 41,
        },
        {
            "name": "FG_textManyWays_Image_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 600,
            "y": 358,
        },

        {
            "name": "Text_amount_tickup_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 920,
            "y": 680,
        },
        {
            "name": "Text_amount_tickup_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 550,
            "y": 873,
        },

        {
            "name": "text_WinCelebration_label_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 940,
            "y": 475,
        },
        {
            "name": "text_WinCelebration_label_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 551,
            "y": 937,
        },
        {
            "name": "text_WinCelebration_label_mobile_portrait",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 940,
            "y": 475,
        },
        {
            "name": "text_WinCelebration_label_mobile_portrait",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 551,
            "y": 653,
        },
        {
            "name": "bgSpine_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 932,
            "y": 550,
        },
        {
            "name": "bgSpine_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 550,
            "y": 700,
        },
       
        {
            "name": "leftCaveMaskImage_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 356,
            "y": 63
        },
        {
            "name": "leftCaveMaskImage_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 14,
            "y": 366
        },
        {
            "name": "rightCaveMaskImage_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1404,
            "y": 63
        },
        {
            "name": "rightCaveMaskImage_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 923,
            "y": 366
        },
        {
            "name": "btn_introBanner_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 940,
            "y": 825,
        },
        {
            "name": "btn_introBanner_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 530,
            "y": 1075,
        },
       
        {
            "name": "introBg_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 950,
            "y": 450,
        },
        {
            "name": "introBg_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 545,
            "y": 699,
        },
        {
            "name": "mountainImage_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 970,
            "y": 500,
        },
        {
            "name": "mountainImage_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 562,
            "y": 750,
        },
       
        {
            "name": "text_IntroScreenFG_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 948,
            "y": 318,
        },
        {
            "name": "text_IntroScreenFG_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 542,
            "y": 567,
        },
        {
            "name": "text_freeSpinAward_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 948,
            "y": 426,
        },
        {
            "name": "text_freeSpinAward_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 543,
            "y": 674,
        },
        {
            "name": "text_2_intro_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 958,
            "y": 660,
        },
        {
            "name": "text_2_intro_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 550,
            "y": 911,
        },
        {
            "name": "text_3_intro_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 1133,
            "y": 540,
        },
        {
            "name": "text_3_intro_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 727,
            "y": 785,
        },
       
        {
            "name": "postIntro_continueButton_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 715,
            "y": 915,
        },

        {
            "name": "postIntro_continueButton_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 294,
            "y": 927
        },
        {
            "name": "Text_Continue_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 963,
            "y": 970,
        },

        {
            "name": "Text_Continue_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 540,
            "y": 983
        },

        {
            "name": "blastAnim_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 895,
            "y": 558,
        },
        {
            "name": "blastAnim_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": false,
            "x": 550,
            "y": 750,
        },

        {
            "name": "amount_tickup_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 960,
            "y": 618,
        },
        {
            "name": "amount_tickup_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 534,
            "y": 872,
        },
   
        {
            "name": "winShower_Container_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },

        {
            "name": "winShower_Container_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": -350,
            "y": 460,
        },



        {
            "name": "winCelebration_Container_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },

        {
            "name": "winCelebration_Container_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": -350,
            "y": 440,
        },

        //outroBImage_mobile

        {
            "name": "mobileBigTextContainer",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 340,
            "y": 337,
        },

        {
            "name": "mobileBigTextContainer",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": -78,
            "y": 568,
        },

        {
            "name": "soundText_mobile",
            "screenMode": "Landscape",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": 0,
            "y": 0,
        },
        {
            "name": "soundText_mobile",
            "screenMode": "Portrait",
            "handMode": "right",
            "uiMode": "mobile",
            "visible": true,
            "x": -400,
            "y": 500,
        },

    ]
}