import React from "react";


interface IframeworkSoundText {
    data: {}
}

export const frameworkSoundText: IframeworkSoundText = {
    data: {
        "COMPONENTS": [
            {
                "id": "soundText_desktop",
                "name": "soundText_desktop",
                "type": "Container",
                "class": "",
                "x": 0,
                "y": 0,
                "layout": false,
                "uimode": "desktop",
                "filterTypes": [],
                child: [
                    {
                        "id": "text_0",
                        "name": "soundText_0",
                        "type": "Text",
                        "x": 900,
                        "y": 100,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_1",
                        "name": "soundText_1",
                        "type": "Text",
                        "x": 900,
                        "y": 150,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_2",
                        "name": "soundText_2",
                        "type": "Text",
                        "x": 900,
                        "y": 200,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_3",
                        "name": "soundText_3",
                        "type": "Text",
                        "x": 900,
                        "y": 250,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_4",
                        "name": "soundText_4",
                        "type": "Text",
                        "x": 900,
                        "y": 300,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_5",
                        "name": "soundText_5",
                        "type": "Text",
                        "x": 900,
                        "y": 350,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_6",
                        "name": "soundText_6",
                        "type": "Text",
                        "x": 900,
                        "y": 400,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_7",
                        "name": "soundText_7",
                        "type": "Text",
                        "x": 900,
                        "y": 450,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_8",
                        "name": "soundText_8",
                        "type": "Text",
                        "x": 900,
                        "y": 500,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_9",
                        "name": "soundText_9",
                        "type": "Text",
                        "x": 900,
                        "y": 550,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_10",
                        "name": "soundText_10",
                        "type": "Text",
                        "x": 900,
                        "y": 600,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_11",
                        "name": "soundText_11",
                        "type": "Text",
                        "x": 900,
                        "y": 650,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_12",
                        "name": "soundText_12",
                        "type": "Text",
                        "x": 900,
                        "y": 700,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_13",
                        "name": "soundText_13",
                        "type": "Text",
                        "x": 900,
                        "y": 750,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_14",
                        "name": "soundText_14",
                        "type": "Text",
                        "x": 900,
                        "y": 800,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                ]
            },
            {
                "id": "soundText_mobile",
                "name": "soundText_mobile",
                "type": "Container",
                "class": "",
                "x": 0,
                "y": 0,
                "layout": true,
                "uimode": "mobile",
                "filterTypes": [],
                child: [
                    {
                        "id": "text_0",
                        "name": "soundText_0",
                        "type": "Text",
                        "x": 900,
                        "y": 100,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_1",
                        "name": "soundText_1",
                        "type": "Text",
                        "x": 900,
                        "y": 150,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_2",
                        "name": "soundText_2",
                        "type": "Text",
                        "x": 900,
                        "y": 200,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_3",
                        "name": "soundText_3",
                        "type": "Text",
                        "x": 900,
                        "y": 250,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_4",
                        "name": "soundText_4",
                        "type": "Text",
                        "x": 900,
                        "y": 300,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_5",
                        "name": "soundText_5",
                        "type": "Text",
                        "x": 900,
                        "y": 350,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_6",
                        "name": "soundText_6",
                        "type": "Text",
                        "x": 900,
                        "y": 400,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_7",
                        "name": "soundText_7",
                        "type": "Text",
                        "x": 900,
                        "y": 450,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_8",
                        "name": "soundText_8",
                        "type": "Text",
                        "x": 900,
                        "y": 500,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_9",
                        "name": "soundText_9",
                        "type": "Text",
                        "x": 900,
                        "y": 550,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_10",
                        "name": "soundText_10",
                        "type": "Text",
                        "x": 900,
                        "y": 600,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_11",
                        "name": "soundText_11",
                        "type": "Text",
                        "x": 900,
                        "y": 650,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_12",
                        "name": "soundText_12",
                        "type": "Text",
                        "x": 900,
                        "y": 700,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_13",
                        "name": "soundText_13",
                        "type": "Text",
                        "x": 900,
                        "y": 750,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                    {
                        "id": "text_14",
                        "name": "soundText_14",
                        "type": "Text",
                        "x": 900,
                        "y": 800,
                        "width": 1000,
                        "visible": true,
                        "text": "QWERREWWWWERREEREEEEEEW",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 46,
                            fontWeight: 'bold',
                            fill: ['#ffffff'],

                        },
                    },
                ]
            },

        ],
    }

};
export const soundTextConfigurationContext = React.createContext(
    {}
);