import React from "react";
import { objectTypes } from "../../../core/components/buttonpanel/interface/Ibuttons";


interface IframeworkCanvasDesktopSettingPanel {
    data: {}

}

export const frameworkCanvasDesktopSettingPanel: IframeworkCanvasDesktopSettingPanel = {

    data: {
        "COMPONENTS": [
            {
                "name": "settingPanel_settingFrameImage",
                "image": "settingPanelFrameImage",
                "type": "Image",
                "class": "",
                "visible": true,
                "width": 1252,
                "height": 823,
                "x": 334,
                "y": 134,
            },
            {
                "id": "settingPanelHeading",
                "name": "settingPanelHeading",
                "type": "Text",
                "x": 955,
                "y": 208,
                "width": 1200,
                "visible": true,
                "text": "desktopSettingPanel_Text_0",
                "scaleToFit": true,
                "anchor": [0.5, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 52,
                    fontWeight: 'bold',
                    fill: '#ffffff',
                },
            },

            {
                "id": "settingHeading2",
                "name": "settingHeading2",
                "type": "Text",
                "x": 974,
                "y": 308,
                "width": 800,
                "visible": true,
                "text": "desktopSettingPanel_Text_1",
                "scaleToFit": true,
                "anchor": [0.5, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 32,
                    fill: '#ffffff',
                },
            },
            {
                "name": "settingImage",
                "image": "settingIconImage",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": true,
                "anchor": [0.5, 0.5],
                "width": 36,
                "height": 36,
                "x": 775,
                "y": 308,
            },
            {
                "id": "showIntroScreenText",
                "name": "showIntroScreenText",
                "type": "Text",
                "x": 550,
                "y": 411,
                "width": 800,
                "visible": true,
                "text": "desktopSettingPanel_Text_2",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 29,
                    fill: '#ffffff',
                    wordWrap: true,
                    wordWrapWidth: 300,
                },
            },
            {
                "id": "introScreenRadioButtonOn",
                "name": "introScreenRadioButtonOn",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 500,
                "y": 411,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_on.png',
                    out: 'raido_btn_on.png',
                    down: 'raido_btn_on.png',
                    disable: 'raido_btn_on.png',
                    enable: 'raido_btn_on.png',
                    hover: 'raido_btn_on.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "introScreenRadioButtonOff",
                "name": "introScreenRadioButtonOff",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 500,
                "y": 411,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_off.png',
                    out: 'raido_btn_off.png',
                    down: 'raido_btn_off.png',
                    disable: 'raido_btn_off.png',
                    enable: 'raido_btn_off.png',
                    hover: 'raido_btn_off.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },

            {
                "name": "introScreenRadioButtonDisable",
                "image": "raido_btn_disable.png",
                "type": objectTypes.Sprite,
                "layout": false,
                "uimode": "desktop",
                "visible": false,
                "width": 78,
                "height": 44,
                "x": 749,
                "y": 391,
            },
            {
                "id": "fullScreenText",
                "name": "fullScreenText",
                "type": "Text",
                "x": 1130,
                "y": 411,
                "width": 280,
                "visible": true,
                "text": "desktopSettingPanel_Text_3",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 29,
                    fill: '#ffffff',
                },
            },
            {
                "id": "fullScreenRadioButtonOn",
                "name": "fullScreenRadioButtonOn",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 1080,
                "y": 411,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_on.png',
                    out: 'raido_btn_on.png',
                    down: 'raido_btn_on.png',
                    disable: 'raido_btn_on.png',
                    enable: 'raido_btn_on.png',
                    hover: 'raido_btn_on.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "fullScreenRadioButtonOff",
                "name": "fullScreenRadioButtonOff",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 1080,
                "y": 411,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_off.png',
                    out: 'raido_btn_off.png',
                    down: 'raido_btn_off.png',
                    disable: 'raido_btn_off.png',
                    enable: 'raido_btn_off.png',
                    hover: 'raido_btn_off.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "name": "fullScreenRadioButtonDisable",
                "image": "raido_btn_disable.png",
                "anchor": [0.5, 0.5],
                "type": objectTypes.Sprite,
                "layout": false,
                "uimode": "desktop",
                "visible": false,
                "width": 78,
                "height": 44,
                "x": 1080,
                "y": 411,
            },

            {
                "id": "soundHeading",
                "name": "soundHeading",
                "type": "Text",
                "x": 517,
                "y": 581,
                "width": 700,
                "visible": true,
                "text": "desktopSettingPanel_Text_4",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 29,
                    fill: '#ffffff',
                },
            },
            {
                "name": "soundImage",
                "image": "soundIconImage",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": true,
                "width": 36,
                "height": 36,
                "x": 467,
                "y": 563,
            },


            {
                "id": "spinHeading",
                "name": "spinHeading",
                "type": "Text",
                "x": 1100,
                "y": 581,
                "width": 700,
                "visible": true,
                "text": "desktopSettingPanel_Text_6",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 29,
                    fill: '#ffffff',
                },
            },
            {
                "name": "spinImage",
                "image": "autoplayIconImage",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": true,
                "width": 36,
                "height": 36,
                "x": 1050,
                "y": 563,
            },


            {
                "id": "musicText",
                "name": "musicText",
                "type": "Text",
                "x": 550,
                "y": 681,
                "width": 820,
                "visible": true,
                "text": "desktopSettingPanel_Text_5",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 31,
                    fill: '#ffffff',
                },
            },
            {
                "id": "musicRadioButtonOn",
                "name": "musicRadioButtonOn",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 500,
                "y": 681,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_on.png',
                    out: 'raido_btn_on.png',
                    down: 'raido_btn_on.png',
                    disable: 'raido_btn_on.png',
                    enable: 'raido_btn_on.png',
                    hover: 'raido_btn_on.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "musicRadioButtonOff",
                "name": "musicRadioButtonOff",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 500,
                "y": 681,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_off.png',
                    out: 'raido_btn_off.png',
                    down: 'raido_btn_off.png',
                    disable: 'raido_btn_off.png',
                    enable: 'raido_btn_off.png',
                    hover: 'raido_btn_off.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "spaceBarToSpinText",
                "name": "spaceBarToSpinText",
                "type": "Text",
                "x": 1130,
                "y": 667,
                "width": 370,
                "visible": true,
                "text": "desktopSettingPanel_Text_7",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 29,
                    fill: '#ffffff',
                    wordWrap: true,
                    wordWrapWidth: 370,
                },
            },
            {
                "id": "spaceBarToSpinRadioButtonOn",
                "name": "spaceBarToSpinRadioButtonOn",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 1080,
                "y": 667,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_on.png',
                    out: 'raido_btn_on.png',
                    down: 'raido_btn_on.png',
                    disable: 'raido_btn_on.png',
                    enable: 'raido_btn_on.png',
                    hover: 'raido_btn_on.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "spaceBarToSpinRadioButtonOff",
                "name": "spaceBarToSpinRadioButtonOff",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 1080,
                "y": 667,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_off.png',
                    out: 'raido_btn_off.png',
                    down: 'raido_btn_off.png',
                    disable: 'raido_btn_off.png',
                    enable: 'raido_btn_off.png',
                    hover: 'raido_btn_off.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            
            {
                "id": "turboSpinText",
                "name": "turboSpinText",
                "type": "Text",
                "x": 1130,
                "y": 730,
                "width": 790,
                "visible": true,
                "text": "desktopSettingPanel_Text_8",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 29,
                    fill: '#ffffff',
                },
            },
            {
                "id": "turboSpinRadioButtonOn",
                "name": "turboSpinRadioButtonOn",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 1080,
                "y": 730,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_on.png',
                    out: 'raido_btn_on.png',
                    down: 'raido_btn_on.png',
                    disable: 'raido_btn_on.png',
                    enable: 'raido_btn_on.png',
                    hover: 'raido_btn_on.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "turboSpinRadioButtonOff",
                "name": "turboSpinRadioButtonOff",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 1080,
                "y": 730,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_off.png',
                    out: 'raido_btn_off.png',
                    down: 'raido_btn_off.png',
                    disable: 'raido_btn_off.png',
                    enable: 'raido_btn_off.png',
                    hover: 'raido_btn_off.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "name": "musicRadioButtonDisable",
                "image": "raido_btn_disable.png",
                "anchor": [0.5, 0.5],
                "type": objectTypes.Sprite,
                "layout": false,
                "uimode": "desktop",
                "visible": false,
                "width": 78,
                "height": 44,
                "x": 500,
                "y": 681,
            },

            {
                "name": "turboSpinRadioButtonDisable",
                "image": "raido_btn_disable.png",
                "type": objectTypes.Sprite,
                "layout": false,
                "uimode": "desktop",
                "visible": false,
                "anchor": [0.5, 0.5],
                "width": 78,
                "height": 44,
                "x": 1080,
                "y": 730,
            },
            {
                "name": "turboSpinRadioButtonDisable",
                "image": "raido_btn_disable.png",
                "type": objectTypes.Sprite,
                "layout": false,
                "uimode": "desktop",
                "visible": false,
                "anchor": [0.5, 0.5],
                "width": 78,
                "height": 44,
                "x": 1080,
                "y": 730,
            },
            {
                "id": "crossButton",
                "name": "crossButton",
                "type": objectTypes.Sprite,
                "buttonMode": true,
                "interactive": true,
                "x": 1500,
                "y": 164,
                "height": 54,
                "width": 54,
                "text": "",
                "visible": true,
                "buttonState": {
                    up: 'cross_btn_up.png',
                    out: 'cross_btn_up.png',
                    down: 'cross_btn_down.png',
                    disable: 'cross_btn_disable.png',
                    enable: 'cross_btn_up.png',
                    hover: 'cross_btn_over.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },


        ],
    }
};

export const CanvasDesktopSettingPanelConfigurationContext = React.createContext(
    {}
);