import React from "react";
import { objectTypes } from "../../../core/components/buttonpanel/interface/Ibuttons";


interface IframeworkCanvasAutoplayPortrait {
    data: {}

}

export const frameworkCanvasAutoplay: IframeworkCanvasAutoplayPortrait = {

    data: {
        "COMPONENTS": [
            {
                "id": "gameScrollComponentMobAutoPlay_landscape",
                "name": "gameScrollComponentMobAutoPlay_landscape",
                "type": "Container",
                "x": 0,
                "y": 0,
                "visible": true,
                "layout": true,
                "uimode": "mobile",
                "filterTypes": [],
                child: [
                    {
                        "id": "autoplayContent",
                        "name": "autoplayContent",
                        "type": "Container",
                        "x": -13,
                        "y": -11,
                        "anchor": [0.5, 0.5],
                        "visible": true,
                        "layout": true,
                        "uimode": "mobile",
                        "filterTypes": [],
                        child: [
                            
        
        
                              {
                                 "id": "countMinus_1",
                                "name": "countMinus_1",
                                "type": objectTypes.Sprite,
                                "interactive": false,
                                "width": 57,
                                "height": 58,
                                "x": 950,
                                "y": 1002,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'minus_p.png',
                                    out: 'minus_p.png',
                                    down: 'minus_p.png',
                                    disable: 'minus_p.png',
                                    enable: 'minus_p.png',
                                    hover: 'minus_p.png'
                                },
                                "hitareaVisible": false,
                                 "shapeVisible": false,
                                 "shape": {}
                             }, 
                            {
                                "id": "countPlus_1",
                                "name": "countPlus_1",
                                "type": objectTypes.Sprite,
                                "interactive": false,
                                "x": 1030,
                                "y": 1002,
                                "width": 57,
                                "height": 58,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'plus_p.png',
                                    out: 'plus_p.png',
                                    down: 'plus_p.png',
                                    disable: 'plus_p.png',
                                    enable: 'plus_p.png',
                                    hover: 'plus_p.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "countMinus_2",
                                "name": "countMinus_2",
                                "type": objectTypes.Sprite,
                                "interactive": false,
                                "x": 950,
                                "y": 1200,
                                "width": 57,
                                "height": 58,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'minus_p.png',
                                    out: 'minus_p.png',
                                    down: 'minus_p.png',
                                    disable: 'minus_p.png',
                                    enable: 'minus_p.png',
                                    hover: 'minus_p.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "countPlus_2",
                                "name": "countPlus_2",
                                "type": objectTypes.Sprite,
                                "interactive": false,
                                "x": 1030,
                                "y": 1200,
                                "width": 57,
                                "height": 58,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'plus_p.png',
                                    out: 'plus_p.png',
                                    down: 'plus_p.png',
                                    disable: 'plus_p.png',
                                    enable: 'plus_p.png',
                                    hover: 'plus_p.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
        
        
                            {
                                "id": "countMinus_3",
                                "name": "countMinus_3",
                                "type": objectTypes.Sprite,
                                "interactive": false,
                                "x": 950,
                                "y": 1404,
                                "width": 57,
                                "height": 58,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'minus_p.png',
                                    out: 'minus_p.png',
                                    down: 'minus_p.png',
                                    disable: 'minus_p.png',
                                    enable: 'minus_p.png',
                                    hover: 'minus_p.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "countPlus_3",
                                "name": "countPlus_3",
                                "type": objectTypes.Sprite,
                                "interactive": false,
                                "x": 1030,
                                "y": 1404,
                                "width": 57,
                                "height": 58,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'plus_p.png',
                                    out: 'plus_p.png',
                                    down: 'plus_p.png',
                                    disable: 'plus_p.png',
                                    enable: 'plus_p.png',
                                    hover: 'plus_p.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
        
        
        
        
        
        
                            {
                                "id": "portraitAutoplayButton1",
                                "name": "portraitAutoplayButton1",
                                "type": objectTypes.Sprite,
                                "interactive": false,
                                "x": 150,
                                "y": 300,
                                "width": 151,
                                "height": 100,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landautoplay_box.png',
                                    out: 'landautoplay_box.png',
                                    down: 'landautoplay_box_up.png',
                                    disable: 'landautoplay_box.png',
                                    enable: 'landautoplay_box.png',
                                    hover: 'landautoplay_box.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_autoplayButtonText1",
                                "name": "portrait_autoplayButtonText1",
                                "type": "Text",
                                "x": 150,
                                "y": 300,
                                "width": 100,
                                "height": 80,
                                "text": "0",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "scaleToFit": true,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 40,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                            },
                            {
                                "id": "portraitAutoplayButton2",
                                "name": "portraitAutoplayButton2",
                                "type": objectTypes.Sprite,
                                "interactive": false,
                                "x": 350,
                                "y": 300,
                                "width": 151,
                                "height": 100,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landautoplay_box.png',
                                    out: 'landautoplay_box.png',
                                    down: 'landautoplay_box_up.png',
                                    disable: 'landautoplay_box.png',
                                    enable: 'landautoplay_box.png',
                                    hover: 'landautoplay_box.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_autoplayButtonText2",
                                "name": "portrait_autoplayButtonText2",
                                "type": "Text",
                                "x": 350,
                                "y": 300,
                                "width": 100,
                                "height": 80,
                                "text": "5",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "scaleToFit": true,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 40,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                            },
                            {
                                "id": "portraitAutoplayButton3",
                                "name": "portraitAutoplayButton3",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "x": 550,
                                "y": 300,
                                "width": 151,
                                "height": 100,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landautoplay_box.png',
                                    out: 'landautoplay_box.png',
                                    down: 'landautoplay_box_up.png',
                                    disable: 'landautoplay_box.png',
                                    enable: 'landautoplay_box.png',
                                    hover: 'landautoplay_box.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_autoplayButtonText3",
                                "name": "portrait_autoplayButtonText3",
                                "type": "Text",
                                "x": 550,
                                "y": 300,
                                "width": 100,
                                "height": 80,
                                "text": "50",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "scaleToFit": true,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 40,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                            },
                            {
                                "id": "portraitAutoplayButton4",
                                "name": "portraitAutoplayButton4",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "x": 750,
                                "y": 300,
                                "width": 151,
                                "height": 100,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landautoplay_box.png',
                                    out: 'landautoplay_box.png',
                                    down: 'landautoplay_box_up.png',
                                    disable: 'landautoplay_box.png',
                                    enable: 'landautoplay_box.png',
                                    hover: 'landautoplay_box.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_autoplayButtonText4",
                                "name": "portrait_autoplayButtonText4",
                                "type": "Text",
                                "x": 750,
                                "y": 300,
                                "width": 100,
                                "height": 80,
                                "text": "50",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "scaleToFit": true,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 40,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                            },
                            {
                                "id": "portraitAutoplayButton5",
                                "name": "portraitAutoplayButton5",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "x": 950,
                                "y": 300,
                                "width": 151,
                                "height": 100,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landautoplay_box.png',
                                    out: 'landautoplay_box.png',
                                    down: 'landautoplay_box_up.png',
                                    disable: 'landautoplay_box.png',
                                    enable: 'landautoplay_box.png',
                                    hover: 'landautoplay_box.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_autoplayButtonText5",
                                "name": "portrait_autoplayButtonText5",
                                "type": "Text",
                                "x": 950,
                                "y": 300,
                                "width": 100,
                                "height": 80,
                                "text": "50",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "scaleToFit": true,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 40,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                            },
                            {
                                "id": "portraitAutoplayButton6",
                                "name": "portraitAutoplayButton6",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "x": 150,
                                "y": 450,
                                "width": 151,
                                "height": 100,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landautoplay_box.png',
                                    out: 'landautoplay_box.png',
                                    down: 'landautoplay_box_up.png',
                                    disable: 'landautoplay_box.png',
                                    enable: 'landautoplay_box.png',
                                    hover: 'landautoplay_box.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_autoplayButtonText6",
                                "name": "portrait_autoplayButtonText6",
                                "type": "Text",
                                "x": 150,
                                "y": 450,
                                "width": 100,
                                "height": 80,
                                "text": "   ",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "scaleToFit": true,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 40,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                            },
                            {
                                "id": "portraitAutoplayButton7",
                                "name": "portraitAutoplayButton7",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "x": 350,
                                "y": 450,
                                "width": 151,
                                "height": 100,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landautoplay_box.png',
                                    out: 'landautoplay_box.png',
                                    down: 'landautoplay_box_up.png',
                                    disable: 'landautoplay_box.png',
                                    enable: 'landautoplay_box.png',
                                    hover: 'landautoplay_box.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_autoplayButtonText7",
                                "name": "portrait_autoplayButtonText7",
                                "type": "Text",
                                "x": 350,
                                "y": 450,
                                "width": 100,
                                "height": 80,
                                "text": " ",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "scaleToFit": true,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 40,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                            },
                            {
                                "id": "portraitAutoplayButton8",
                                "name": "portraitAutoplayButton8",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "x": 550,
                                "y": 450,
                                "width": 151,
                                "height": 100,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landautoplay_box.png',
                                    out: 'landautoplay_box.png',
                                    down: 'landautoplay_box_up.png',
                                    disable: 'landautoplay_box.png',
                                    enable: 'landautoplay_box.png',
                                    hover: 'landautoplay_box.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_autoplayButtonText8",
                                "name": "portrait_autoplayButtonText8",
                                "type": "Text",
                                "x": 550,
                                "y": 450,
                                "width": 100,
                                "height": 80,
                                "text": " ",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "scaleToFit": true,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 40,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                            },
                            {
                                "id": "portraitAutoplayButton9",
                                "name": "portraitAutoplayButton9",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "x": 750,
                                "y": 450,
                                "width": 151,
                                "height": 100,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landautoplay_box.png',
                                    out: 'landautoplay_box.png',
                                    down: 'landautoplay_box_up.png',
                                    disable: 'landautoplay_box.png',
                                    enable: 'landautoplay_box.png',
                                    hover: 'landautoplay_box.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_autoplayButtonText9",
                                "name": "portrait_autoplayButtonText9",
                                "type": "Text",
                                "x": 750,
                                "y": 450,
                                "width": 100,
                                "height": 80,
                                "text": " ",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "scaleToFit": true,
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 40,
                                    fontStyle: 'normal',
                                    fontWeight: 'bold',
                                    fill: ['#ffffff'],
                                },
                            },
                            {
                                "id": "bottomSpritLineMobilePortrait1",
                                "name": "bottomSpritLineMobilePortrait1",
                                "image": "landhorizontal_line.png",
                                "type": "Image",
                                "uimode": "mobile",
                                "layout": true,
                                "visible": true,
                                "x": 0,
                                "y": 580,
                                "width": 1920,
                                "height": 4,
                            },
                            {
                                "id": "stopAutoplayTextPortrait",
                                "name": "stopAutoplayTextPortrait",
                                "type": "Text",
                                "x": 220,
                                "y": 700,
                                "width": 400,
                                "height": 400,
                                "visible": true,
                                "text": "autoplayText_2",
                                "scaleToFit": true,
                                "anchor": [0.5, 0.5],
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fill: '#ffffff',
                                },
                            },
                            {
                                "id": "radioButtonOffPortrait",
                                "name": "radioButtonOffPortrait",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "width": 150,
                                "height": 50,
                                "x": 165,
                                "y": 800,
                                "text": "",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landradio_btn_off.png',
                                    out: 'landradio_btn_off.png',
                                    down: 'landradio_btn_off.png',
                                    disable: 'landradio_btn_off.png',
                                    enable: 'landradio_btn_off.png',
                                    hover: 'landradio_btn_off.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "radioButtonOnPortrait",
                                "name": "radioButtonOnPortrait",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "width": 150,
                                "height": 50,
                                "x": 165,
                                "y": 800,
                                "text": "",
                                "anchor": [0.5, 0.5],
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landradio_btn_on.png',
                                    out: 'landradio_btn_on.png',
                                    down: 'landradio_btn_on.png',
                                    disable: 'landradio_btn_on.png',
                                    enable: 'landradio_btn_on.png',
                                    hover: 'landradio_btn_on.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "onAnyWinTextPortrait",
                                "name": "onAnyWinTextPortrait",
                                "type": "Text",
                                "x": 415,
                                "y": 800,
                                "width": 400,
                                "height": 400,
                                "visible": true,
                                "text": "autoplayText_3",
                                "scaleToFit": true,
                                "anchor": [0.5, 0.5],
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fill: '#ffffff',
                                },
                            },
                            {
                                "id": "bottomSpritLineMobilePortrait2",
                                "name": "bottomSpritLineMobilePortrait2",
                                "image": "landhorizontal_line.png",
                                "type": "Image",
                                "uimode": "mobile",
                                "layout": true,
                                "visible": true,
                                "x": 0,
                                "y": 920,
                                "width": 1920,
                                "height": 4,
                            },
                            {
                                "id": "portrait_sliderLineBG",
                                "name": "portrait_sliderLineBG",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "width": 743,
                                "height": 18,
                                "x": 95,
                                "y": 1060,
                                "text": "",
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'slider_base.png',
                                    out: 'slider_base.png',
                                    down: 'slider_base.png',
                                    disable: 'slider_base.png',
                                    enable: 'slider_base.png',
                                    hover: 'slider_base.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_sliderLine_2BG",
                                "name": "portrait_sliderLine_2BG",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "width": 743,
                                "height": 18,
                                "x": 95,
                                "y": 1260,
                                "text": "",
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'slider_base.png',
                                    out: 'slider_base.png',
                                    down: 'slider_base.png',
                                    disable: 'slider_base.png',
                                    enable: 'slider_base.png',
                                    hover: 'slider_base.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_sliderLine_3BG",
                                "name": "portrait_sliderLine_3BG",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "width": 743,
                                "height": 18,
                                "x": 95,
                                "y": 1460,
                                "text": "",
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'slider_base.png',
                                    out: 'slider_base.png',
                                    down: 'slider_base.png',
                                    disable: 'slider_base.png',
                                    enable: 'slider_base.png',
                                    hover: 'slider_base.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_sliderDot_inputBoxText",
                                "name": "portrait_sliderDot_inputBoxText",
                                "type": "Text",
                                "x": 830,
                                "y": 1002,
                                "width": 400,
                                "height": 400,
                                "visible": true,
                                "text": "0",
                                "scaleToFit": true,
                                "anchor": [0.5, 0.5],
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontWeight: 'bold',
                                    fill: '#ffffff',
                                },
                            },
                            {
                                "id": "portrait_sliderDot_2_inputBoxText",
                                "name": "portrait_sliderDot_2_inputBoxText",
                                "type": "Text",
                                "x": 830,
                                "y": 1200,
                                "width": 400,
                                "height": 400,
                                "visible": true,
                                "text": "0",
                                "scaleToFit": true,
                                "anchor": [0.5, 0.5],
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontWeight: 'bold',
                                    fill: '#ffffff',
                                },
                            },
                            {
                                "id": "portrait_sliderDot_3_inputBoxText",
                                "name": "portrait_sliderDot_3_inputBoxText",
                                "type": "Text",
                                "x": 830,
                                "y": 1404,
                                "width": 400,
                                "height": 400,
                                "visible": true,
                                "text": "0",
                                "scaleToFit": true,
                                "anchor": [0.5, 0.5],
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fontWeight: 'bold',
                                    fill: '#ffffff',
                                },
                            },
                            {
                                "id": "portrait_sliderDotLine",
                                "name": "portrait_sliderDotLine",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "width": 743,
                                "height": 18,
                                "x": 95,
                                "y": 1060,
                                "text": "",
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'slider_top.png',
                                    out: 'slider_top.png',
                                    down: 'slider_top.png',
                                    disable: 'slider_top.png',
                                    enable: 'slider_top.png',
                                    hover: 'slider_top.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_sliderDot_2Line",
                                "name": "portrait_sliderDot_2Line",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "width": 743,
                                "height": 18,
                                "x": 95,
                                "y": 1260,
                                "text": "",
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'slider_top.png',
                                    out: 'slider_top.png',
                                    down: 'slider_top.png',
                                    disable: 'slider_top.png',
                                    enable: 'slider_top.png',
                                    hover: 'slider_top.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "portrait_sliderDot_3Line",
                                "name": "portrait_sliderDot_3Line",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "width": 743,
                                "height": 18,
                                "x": 95,
                                "y": 1460,
                                "text": "",
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'slider_top.png',
                                    out: 'slider_top.png',
                                    down: 'slider_top.png',
                                    disable: 'slider_top.png',
                                    enable: 'slider_top.png',
                                    hover: 'slider_top.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
        
                            {
                                "name": "portrait_sliderDot",
                                "image": "cir_ld.png",
                                "type": "Image",
                                "class": "",
                                "filterTypes": [],
                                "visible": true,
                                "width": 54,
                                "height": 54,
                                "x": 95,
                                "y": 1040
                            },
                            {
                                "name": "portrait_sliderDot_2",
                                "image": "cir_ld.png",
                                "type": "Image",
                                "class": "",
                                "filterTypes": [],
                                "visible": true,
                                "width": 54,
                                "height": 54,
                                "x": 95,
                                "y": 1240
                            },
                            {
                                "name": "portrait_sliderDot_3",
                                "image": "cir_ld.png",
                                "type": "Image",
                                "class": "",
                                "filterTypes": [],
                                "visible": true,
                                "width": 54,
                                "height": 54,
                                "x": 95,
                                "y": 1440
                            },
                            {
                                "name": "portrait_sliderDot_disable",
                                "image": "cir_ld_dim.png",
                                "type": "Image",
                                "class": "",
                                "filterTypes": [],
                                "visible": false,
                                "width": 54,
                                "height": 54,
                                "x": 95,
                                "y": 1040
                            },
                            {
                                "name": "portrait_sliderDot_2_disable",
                                "image": "cir_ld_dim.png",
                                "type": "Image",
                                "class": "",
                                "filterTypes": [],
                                "visible": false,
                                "width": 54,
                                "height": 54,
                                "x": 95,
                                "y": 1240
                            },
                            {
                                "name": "portrait_sliderDot_3_disable",
                                "image": "cir_ld_dim.png",
                                "type": "Image",
                                "class": "",
                                "filterTypes": [],
                                "visible": false,
                                "width": 54,
                                "height": 54,
                                "x": 95,
                                "y": 1440
                            },
                            {
                                "id": "ifSingleWinExceedTextPortrait",
                                "name": "ifSingleWinExceedTextPortrait",
                                "type": "Text",
                                "x": 95,
                                "y": 1000,
                                "width": 750,
                                "height": 400,
                                "visible": true,
                                "text": "autoplayText_6",
                                "scaleToFit": true,
                                "anchor": [0, 0.5],
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 42,
                                    fill: '#ffffff',
                                },
                            },
                            {
                                "id": "ifBalanceIncreaseByTextPortrait",
                                "name": "ifBalanceIncreaseByTextPortrait",
                                "type": "Text",
                                "x": 95,
                                "y": 1200,
                                "width": 750,
                                "height": 400,
                                "visible": true,
                                "text": "autoplayText_7",
                                "scaleToFit": true,
                                "anchor": [0, 0.5],
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 42,
                                    fill: '#ffffff',
                                },
                            },
                            {
                                "id": "ifBalanceDecreaseByTextPortrait",
                                "name": "ifBalanceDecreaseByTextPortrait",
                                "type": "Text",
                                "x": 95,
                                "y": 1400,
                                "width": 750,
                                "height": 400,
                                "visible": true,
                                "text": "autoplayText_8",
                                "scaleToFit": true,
                                "anchor": [0, 0.5],
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 42,
                                    fill: '#ffffff',
                                },
                            },
                            {
                                "id": "autoplayBtnDisablePortrait",
                                "name": "autoplayBtnDisablePortrait",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "width": 520,
                                "height": 120,
                                "x": 270,
                                "y": 1600,
                                "text": "",
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landstart_disable.png',
                                    out: 'landstart_disable.png',
                                    down: 'landstart_disable.png',
                                    disable: 'landstart_disable.png',
                                    enable: 'landstart_disable.png',
                                    hover: 'landstart_disable.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "autoplayStartButtonPortrait",
                                "name": "autoplayStartButtonPortrait",
                                "type": objectTypes.Sprite,
                                "interactive": true,
                                "width": 520,
                                "height": 120,
                                "x": 270,
                                "y": 1600,
                                "visible": true,
                                "buttonMode": true,
                                "buttonState": {
                                    up: 'landstart_up.png',
                                    out: 'landstart_up.png',
                                    down: 'landstart_up.png',
                                    disable: 'landstart_disable.png',
                                    enable: 'landstart_up.png',
                                    hover: 'landstart_up.png'
                                },
                                "hitareaVisible": false,
                                "shapeVisible": false,
                                "shape": {}
                            },
                            {
                                "id": "autoplayStartButtonTextPortrait",
                                "name": "autoplayStartButtonTextPortrait",
                                "type": "Text",
                                "x": 530,
                                "y": 1660,
                                "width": 400,
                                "height": 400,
                                "visible": true,
                                "text": "START AUTOPLAY",
                                "scaleToFit": true,
                                "anchor": [0.5, 0.5],
                                "textStyle": {
                                    fontFamily: 'Arial',
                                    fontSize: 48,
                                    fill: '#ffffff',
                                },
                            },
                        ],
        
                    }
                ]
            },
           
        ]
    }
};

export const CanvasAutoplayPortraitConfigurationContext = React.createContext(
    {}
);