import React from "react";
import { objectTypes } from "../../../core/components/buttonpanel/interface/Ibuttons";

interface IframeworkRealityCheck {
    data: {}
}

export const frameworkRealityCheck: IframeworkRealityCheck = {
    data: {
        "COMPONENTS": [
            {
                "id": "realityCheckContainer_desktop",
                "name": "realityCheckContainer_desktop",
                "type": "Container",
                "class": "",
                "visible": true,
                "uimode": "desktop",
                "x": 0,
                "y": 0,
                "width": 1920,
                "height": 250,
                "filterTypes": [],
                child: [
                    {
                        "name": "realityCheckGraphic",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "visible": true,
                        "alpha": 0.89,
                        "color": "0x000000",
                        "x": 0,
                        "y": 400,
                        "width": 1920,
                        "height": 250,
                    },
                    {
                        "id": "rc_text_1",
                        "name": "rc_text_1",
                        "type": "Text",
                        "x": 980,
                        "y": 435,
                        "width": 350,
                        "visible": true,
                        "text": "realityCheckText1",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 47,
                            fill: ['#ffffff'],
                        },
                    },
                    {
                        "id": "rc_line_1",
                        "name": "rc_line_1",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "color": "0xffffff",
                        "alpha": 0.89,
                        "x": 0,
                        "y": 465,
                        "width": 1920,
                        "height": 4,
                        "visible": true,
                        "scaleToFit": true,
                    },
                    {
                        "id": "rc_text_2",
                        "name": "rc_text_2",
                        "type": "Text",
                        "x": 1025,
                        "y": 494,
                        "width": 900,
                        "visible": true,
                        "text": "realityCheckText5",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 28,
                            fill: ['#ffffff'],
                        },
                    },

                    {
                        "id": "rc_text_7",
                        "name": "rc_text_7",
                        "type": "Text",
                        "x": 1024,
                        "y": 528,
                        "width": 900,
                        "visible": true,
                        "text": "realityCheckText5",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 28,
                            fill: ['#ffffff'],
                        },
                    },
                    {
                        "id": "rc_line_2",
                        "name": "rc_line_2",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "color": "0xffffff",
                        "alpha": 0.89,
                        "x": 0,
                        "y": 550,
                        "width": 1920,
                        "height": 4,
                        "visible": true,
                        "scaleToFit": true,
                    },
                    {
                        "id": "continue_btn_desktop",
                        "name": "continue_btn_desktop",
                        "type": objectTypes.Sprite,
                        "buttonMode": true,
                        "interactive": true,
                        "x": 730,
                        "y": 570,
                        "width": 226,
                        "height": 65,
                        "text": "",
                        "visible": true,
                        "buttonState": {
                            up: 'bet.png',
                            out: 'bet.png',
                            down: 'bet.png',
                            disable: 'bet.png',
                            enable: 'bet.png',
                            hover: 'bet.png'
                        },
                        "hitareaVisible": false,
                        "shapeVisible": false,
                        "shape": {}
                    },

                    {
                        "id": "quit_btn_desktop",
                        "name": "quit_btn_desktop",
                        "type": objectTypes.Sprite,
                        "buttonMode": true,
                        "interactive": true,
                        "x": 985,
                        "y": 570,
                        "width": 226,
                        "height": 65,
                        "text": "",
                        "visible": true,
                        "buttonState": {
                            up: 'bet.png',
                            out: 'bet.png',
                            down: 'bet.png',
                            disable: 'bet.png',
                            enable: 'bet.png',
                            hover: 'bet.png'
                        },
                        "hitareaVisible": false,
                        "shapeVisible": false,
                        "shape": {}
                    },
                    {
                        "id": "rc_text_continue",
                        "name": "rc_text_continue",
                        "type": "Text",
                        "x": 845,
                        "y": 602,
                        "width": 180,
                        "visible": true,
                        "text": "realityCheckText6",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 32,
                            fill: ['#ffffff'],
                        },
                    },
                    {
                        "id": "rc_text_quit",
                        "name": "rc_text_quit",
                        "type": "Text",
                        "x": 1095,
                        "y": 602,
                        "width": 180,
                        "visible": true,
                        "text": "realityCheckText7",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 32,
                            fill: ['#ffffff'],
                        },
                    },
                ]
            },
            {
                "id": "realityCheckContainer_mobile",
                "name": "realityCheckContainer_mobile",
                "type": "Container",
                "class": "",
                "visible": true,
                "layout": true,
                "uimode": "mobile",
                "x": 0,
                "y": 0,
                "width": 1920,
                "height": 250,
                "filterTypes": [],
                "parentLayer": "specialAnimationLayer",
                child: [
                    {
                        "name": "realityCheckGraphic_mobile",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "visible": true,
                        "color": "0x000000",
                        "x": 0,
                        "y": 0,
                        "width": 1920,
                        "height": 250,
                    },
                    {
                        "id": "rc_text_1_mobile",
                        "name": "rc_text_1_mobile",
                        "type": "Text",
                        "x": 1015,
                        "y": 26,
                        "width": 350,
                        "visible": true,
                        "uimode": "mobile",
                        "layout": true,
                        "text": "realityCheckText1",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 47,
                            fill: ['#ffffff'],
                        },
                    },
                    {
                        "id": "rc_line_1_mobile",
                        "name": "rc_line_1_mobile",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "color": "0xffffff",
                        "alpha": 0.89,
                        "x": 0,
                        "y": 55,
                        "width": 1920,
                        "height": 4,
                        "visible": true,
                        "scaleToFit": true,
                    },
                    {
                        "id": "rc_text_2_mobile",
                        "name": "rc_text_2_mobile",
                        "type": "Text",
                        "x": 1025,
                        "y": 85,
                        "width": 900,
                        "uimode": "mobile",
                        "layout": true,
                        "visible": true,
                        "text": "realityCheckText5",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 28,
                            fill: ['#ffffff'],
                        },
                    },

                    {
                        "id": "rc_text_7_mobile",
                        "name": "rc_text_7_mobile",
                        "type": "Text",
                        "x": 1016,
                        "y": 116,
                        "width": 900,
                        "visible": true,
                        "text": "realityCheckText5",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 28,
                            fill: ['#ffffff'],
                        },
                    },
                    {
                        "id": "rc_line_2_mobile",
                        "name": "rc_line_2_mobile",
                        "type": "Graphic",
                        "shape": "rectangle",
                        "color": "0xffffff",
                        "alpha": 0.89,
                        "x": 0,
                        "y": 140,
                        "width": 1920,
                        "height": 4,
                        "visible": true,
                        "scaleToFit": true,
                    },
                    {
                        "id": "continue_btn_mobile",
                        "name": "continue_btn_mobile",
                        "type": objectTypes.Sprite,
                        "buttonMode": true,
                        "interactive": true,
                        "x": 778,
                        "y": 165,
                        "width": 226,
                        "uimode": "mobile",
                        "height": 65,
                        "text": "",
                        "visible": true,
                        "layout": true,
                        "buttonState": {
                            up: 'bet.png',
                            out: 'bet.png',
                            down: 'bet.png',
                            disable: 'bet.png',
                            enable: 'bet.png',
                            hover: 'bet.png'
                        },
                        "hitareaVisible": false,
                        "shapeVisible": false,
                        "shape": {}
                    },

                    {
                        "id": "quit_btn_mobile",
                        "name": "quit_btn_mobile",
                        "type": objectTypes.Sprite,
                        "buttonMode": true,
                        "interactive": true,
                        "uimode": "mobile",
                        "x": 1020,
                        "y": 165,
                        "width": 226,
                        "height": 65,
                        "layout": true,
                        "text": "",
                        "visible": true,
                        "buttonState": {
                            up: 'bet.png',
                            out: 'bet.png',
                            down: 'bet.png',
                            disable: 'bet.png',
                            enable: 'bet.png',
                            hover: 'bet.png'
                        },
                        "hitareaVisible": false,
                        "shapeVisible": false,
                        "shape": {}
                    },
                    {
                        "id": "rc_text_continue_mobile",
                        "name": "rc_text_continue_mobile",
                        "type": "Text",
                        "uimode": "mobile",
                        "x": 892,
                        "y": 197,
                        "width": 180,
                        "visible": true,
                        "layout": true,
                        "text": "realityCheckText6",
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 32,
                            fill: ['#ffffff'],
                        },
                    },
                    {
                        "id": "rc_text_quit_mobile",
                        "name": "rc_text_quit_mobile",
                        "type": "Text",
                        "uimode": "mobile",
                        "x": 1134,
                        "y": 197,
                        "width": 180,
                        "visible": true,
                        "text": "realityCheckText7",
                        "layout": true,
                        "scaleToFit": true,
                        "anchor": [0.5, 0.5],
                        "textStyle": {
                            fontFamily: 'Arial',
                            fontSize: 32,
                            fill: ['#ffffff'],
                        },
                    },
                ]
            }
        ],
    }

};
export const realityCheckConfigurationContext = React.createContext(
    {}
);