import { frameworkFreeGame } from "../../../core/components/freegame/configuration/freegameconfiguration"
import { freegameAssetConfig } from "../../../data/freegame";
import { basegameAssetConfig } from "../../../data/basegame";
import { objectTypes } from "../../../core/components/buttonpanel/interface/Ibuttons";


frameworkFreeGame.data = {

    "POS_X": 0,
    "POS_Y": 0,
    "COMPONENTS": [
        {
            "id": "BMFreeGameContainer_baseLayer",
            "name": "BMFreeGameContainer_baseLayer",
            "type": "Container",
            "class": "",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "parentLayer": "baseLayer",
            child: [
                {
                    "id": "BMFreeGameComponent",
                    "name": "GofFreeGameBaseLayer",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            "name": "FG_thunder_Anim_desktop",
                            "type": "Animation",
                            "width": 606,
                            "height": 577,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "thunder",
                            "parentLayer": "baseLayer",
                            "animationSpeed": 0.2,
                            "playing": true,
                            "loop": false,
                            "visible": false,
                            "anchor": [0, 0],
                            "x": 0,
                            "y": 0,
                            "animations": {
                                "anim": ["thunder"],
                            },
                        },
                        {
                            "name": "FG_thunder_Anim_mobile",
                            "type": "Animation",
                            "width": 606,
                            "height": 577,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "thunder",
                            "parentLayer": "baseLayer",
                            "animationSpeed": 0.2,
                            "playing": true,
                            "loop": false,
                            "visible": false,
                            "anchor": [0, 0],
                            "x": 0,
                            "y": 0,
                            "animations": {
                                "anim": ["thunder"],
                            },
                        },


                        {
                            "name": "frameReel_FG_Image_desktop",
                            "image": "frameReelFG",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "uimode": "desktop",
                            "parentLayer": "baseLayer",
                            "filterTypes": [],
                            "visible": true,
                            "width": 1307,
                            "height": 859,
                            "x": 289.5,
                            "y": 76
                        },
                        {
                            "name": "frameReel_FG_Image_Mob",
                            "image": "frameReelFG",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "uimode": "mobile",
                            "parentLayer": "baseLayer",
                            "filterTypes": [],
                            "visible": true,
                            "width": 1307,
                            "height": 859,
                            "x": 295.5,
                            "y": 76
                        },
                    ]
                }
            ]

        },
        {
            "id": "BMFreeGameContainer_specialLayer",
            "name": "BMFreeGameContainer_specialLayer",
            "type": "Container",
            "class": "",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "parentLayer": "specialAnimationLayer",
            child: [
                {
                    "id": "BMFreeGameComponent",
                    "name": "GofFreeGameSpecialLayer",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [

                        {
                            "name": "frame_FG_Image_desktop",
                            "image": "frameFG",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "uimode": "desktop",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            "visible": true,
                            "width": 1924,
                            "height": 1084,
                            "x": -3.5,
                            "y": 0
                        },
                        {
                            "name": "frame_FG_Image_Mob",
                            "image": "frameFG",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "uimode": "mobile",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            "visible": true,
                            "width": 1924,
                            "height": 1084,
                            "x": -2.5,
                            "y": -3
                        },


                        {
                            "name": "FG_gameLogo_Anim_desktop",
                            "type": "Animation",
                            "width": 324,
                            "height": 334,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "bg_gamelogo",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.5,
                            "playing": false,
                            "loop": false,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 118.5,
                            "y": 186.5,
                            "animations": {
                                "anim": ["bg_gamelogo"],
                            },
                        },
                        {
                            "name": "FG_gameLogo_Anim_mobile",
                            "type": "Animation",
                            "width": 324,
                            "height": 334,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "bg_gamelogo",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.5,
                            "playing": false,
                            "loop": false,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 118.5,
                            "y": 186.5,
                            "animations": {
                                "anim": ["bg_gamelogo"],
                            },
                        },


                        {
                            "id": "FG_coalLoop_Anim_desktop",
                            "name": "FG_coalLoop_Anim_desktop",
                            "type": "Spine",
                            "x": 1807,
                            "y": 360,
                            "width": 128,
                            "height": 122,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "anchor": [0, 0],
                            "spinedata": {
                                "spinename": "FG_coalLoop",
                                "animationname": "animation",
                                "loop": true,
                                "timeScale": 0.5

                            },
                        },
                        {
                            "id": "FG_coalLoop_Anim_mobile",
                            "name": "FG_coalLoop_Anim_mobile",
                            "type": "Spine",
                            "x": 1807,
                            "y": 360,
                            "width": 128,
                            "height": 122,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "anchor": [0, 0],
                            "spinedata": {
                                "spinename": "FG_coalLoop",
                                "animationname": "animation",
                                "loop": true,
                                "timeScale": 0.5

                            },
                        },



                        {
                            "name": "multiplierFrame_FG_Image_desktop",
                            "image": "multiplierFrameFG",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "uimode": "desktop",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            "visible": true,
                            "width": 197,
                            "height": 159,
                            "x": 1712,
                            "y": 391
                        },
                        {
                            "name": "multiplierFrame_FG_Image_mob",
                            "image": "multiplierFrameFG",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "uimode": "mobile",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            "visible": true,
                            "width": 197,
                            "height": 159,
                            "x": 1712,
                            "y": 391
                        },


                        {
                            "name": "FG_leftTorchFlame_Anim_desktop",
                            "type": "Animation",
                            "width": 99,
                            "height": 96,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "FG_torchFlame",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.5,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 136,
                            "y": 684,
                            "animations": {
                                "anim": "FG_torchFlame",
                            },
                        },
                        {
                            "name": "FG_rightTorchFlame_Anim_desktop",
                            "type": "Animation",
                            "width": 99,
                            "height": 96,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "FG_torchFlame",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.5,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 1773,
                            "y": 684,
                            "animations": {
                                "anim": "FG_torchFlame",
                            },
                        },


                        {
                            "name": "FG_Left_DrippingLava0_Anim_desktop",
                            "type": "Animation",
                            "width": 24,
                            "height": 76,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "FG_drippingLava0",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.2,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 292,
                            "y": 338,
                            "animations": {
                                "anim": "FG_drippingLava0",
                            },
                        },
                        {
                            "name": "FG_Right_DrippingLava0_Anim_desktop",
                            "type": "Animation",
                            "width": 24,
                            "height": 76,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "FG_drippingLava0",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.2,
                            "playing": true,
                            "scale": [-1, 1],
                            "loop": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 1624,
                            "y": 338,
                            "animations": {
                                "anim": "FG_drippingLava0",
                            },
                        },


                        {
                            "name": "FG_Left_DrippingLava1_Anim_desktop",
                            "type": "Animation",
                            "width": 260,
                            "height": 834,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "FG_drippingLavaRight1",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.1,
                            "playing": true,
                            "loop": true,
                            "visible": true,

                            "anchor": [0.5, 0.5],
                            "x": 297,
                            "y": 464,
                            "animations": {
                                "anim": ["FG_drippingLavaRight1", "FG_drippingLavaRight2", "FG_drippingLavaRight3"]
                            },
                        },
                        {
                            "name": "FG_Right_DrippingLava1_Anim_desktop",
                            "type": "Animation",
                            "width": 260,
                            "height": 834,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "FG_drippingLavaRight1",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.1,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 1621,
                            "y": 464,
                            "animations": {
                                "anim": ["FG_drippingLavaRight1", "FG_drippingLavaRight2", "FG_drippingLavaRight3"],
                            },
                        },


                        {
                            "id": "FG_smoke_Anim_desktop",
                            "name": "FG_smoke_Anim_desktop",
                            "type": "Spine",
                            "x": 0,
                            "y": 1150,
                            "width": 480,
                            "height": 134,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "anchor": [0, 0],
                            "spinedata": {
                                "spinename": "fg_smoke",
                                "animationname": "animation",
                                "loop": true,
                                "timeScale": 0.5

                            },
                        },
                        {
                            "id": "FG_smoke_Anim_mobile",
                            "name": "FG_smoke_Anim_mobile",
                            "type": "Spine",
                            "x": 0,
                            "y": 1150,
                            "width": 480,
                            "height": 134,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "anchor": [0, 0],
                            "spinedata": {
                                "spinename": "fg_smoke",
                                "animationname": "animation",
                                "loop": true,
                                "timeScale": 0.5

                            },
                        },


                        {
                            "name": "FG_bugFLies_Anim_mobile",
                            "type": "Animation",
                            "width": 960,
                            "height": 540,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "FG_bug_flies_1",
                            "animationSpeed": 0.1,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0, 0],
                            "x": 0,
                            "y": 0,
                            "animations": {
                                "anim": ["FG_bug_flies_1", "FG_bug_flies_2", "FG_bug_flies_3", "FG_bug_flies_4"],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },


                        {
                            "name": "FG_leftTorchFlame_Anim_mobile",
                            "type": "Animation",
                            "width": 99,
                            "height": 96,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "FG_torchFlame",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.5,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 136,
                            "y": 684,
                            "animations": {
                                "anim": "FG_torchFlame",
                            },
                        },
                        {
                            "name": "FG_rightTorchFlame_Anim_mobile",
                            "type": "Animation",
                            "width": 99,
                            "height": 96,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "FG_torchFlame",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.5,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 1773,
                            "y": 684,
                            "animations": {
                                "anim": "FG_torchFlame",
                            },
                        },


                        {
                            "name": "FG_Left_DrippingLava0_Anim_mobile",
                            "type": "Animation",
                            "width": 24,
                            "height": 76,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "FG_drippingLava0",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.2,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 294,
                            "y": 338,
                            "animations": {
                                "anim": "FG_drippingLava0",
                            },
                        },
                        {
                            "name": "FG_Right_DrippingLava0_Anim_mobile",
                            "type": "Animation",
                            "width": 24,
                            "height": 76,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "FG_drippingLava0",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.2,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [-1, 1],
                            "x": 1580,
                            "y": 372,
                            "animations": {
                                "anim": "FG_drippingLava0",
                            },
                        },


                        {
                            "name": "FG_Left_DrippingLava1_Anim_mobile",
                            "type": "Animation",
                            "width": 260,
                            "height": 834,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "FG_drippingLavaRight1",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.1,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 299,
                            "y": 461,
                            "animations": {
                                "anim": ["FG_drippingLavaRight1", "FG_drippingLavaRight2", "FG_drippingLavaRight3"]
                            },
                        },
                        {
                            "name": "FG_Right_DrippingLava1_Anim_mobile",
                            "type": "Animation",
                            "width": 260,
                            "height": 834,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "FG_drippingLavaRight1",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.1,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 1621,
                            "y": 461,
                            "animations": {
                                "anim": ["FG_drippingLavaRight1", "FG_drippingLavaRight2", "FG_drippingLavaRight3"],
                            },
                        },
                        {
                            "name": "middleBarFG_Image",
                            "image": "middleBarFG",
                            "type": "Image",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            "layout": true,
                            "uimode": "desktop",
                            "visible": true,
                            "width": 508,
                            "height": 108,
                            "x": 707,
                            "y": 911
                        },


                        {
                            "id": "text_9_desktop",
                            "name": "text_FreeGame_label",
                            "type": "Text",
                            "x": 854,
                            "y": 895,
                            "width": 370,
                            "text": "freegameText1",
                            "layout": true,
                            "uimode": "desktop",
                            "scaleToFit": true,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 23,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                                align: 'center'
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_10_desktop",
                            "name": "text_FreeGame_value1",
                            "type": "Text",
                            "x": 795,
                            "y": 962,
                            "width": 95,
                            "layout": true,
                            "uimode": "desktop",
                            "text": "00",
                            "scaleToFit": true,
                            "visible": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fontWeight: 'bold',
                                fill: ['#f3f006', '#f3f006', '#f3e20b'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_11_desktop",
                            "name": "text_FreeGame_OF_label",
                            "type": "Text",
                            "x": 835,
                            "y": 962,
                            "width": 70,
                            "text": "freegameText3",
                            "visible": true,
                            "layout": true,
                            "uimode": "desktop",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fontWeight: 'bold',
                                fill: ['#f3f006', '#f3f006', '#f3e20b'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_12_desktop",
                            "name": "text_FreeGame_value2",
                            "type": "Text",
                            "x": 896,
                            "y": 962,
                            "width": 76,
                            "layout": true,
                            "uimode": "desktop",
                            "visible": true,
                            "text": "",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fontWeight: 'bold',
                                fill: ['#f3f006', '#f3f006', '#f3e20b'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },


                        {
                            "id": "text_13_desktop",
                            "name": "text_TotalWin_label",
                            "type": "Text",
                            "x": 1078,
                            "y": 895,
                            "width": 230,
                            "visible": true,
                            "text": "freegameText5",
                            "scaleToFit": true,
                            "layout": true,
                            "uimode": "desktop",
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 23,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_14_desktop",
                            "name": "text_TotalWin_value",
                            "type": "Text",
                            "x": 1078,
                            "y": 962,
                            "width": 220,
                            "text": "000",
                            "layout": true,
                            "uimode": "desktop",
                            "visible": false,
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fill: ['#01f301'],
                                fontWeight: 'bold',
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "name": "button_Panel_Left_BottomBarImage",
                            "image": "buttonPanelLeftBottomBar",
                            "type": "Image",
                            "class": "",
                            "uimode": "desktop",
                            "filterTypes": [],
                            "visible": true,
                            "width": 934,
                            "height": 58,
                            "x": 0,
                            "y": 1022
                        },
                        {
                            "name": "button_Panel_Right_BottomBarImage",
                            "image": "buttonPanelRightBottomBar",
                            "type": "Image",
                            "class": "",
                            "uimode": "desktop",
                            "filterTypes": [],
                            "visible": true,
                            "width": 934,
                            "height": 58,
                            "x": 986,
                            "y": 1022
                        },


                        {
                            "id": "btn_setting",
                            "name": "btn_setting",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "interactive": false,
                            "x": 5,
                            "y": 1025,
                            "height": 64,
                            "width": 64,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'setting_disable.png',
                                out: 'setting_disable.png',
                                down: 'setting_disable.png',
                                disable: 'setting_disable.png',
                                enable: 'setting_disable.png',
                                hover: 'setting_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {},

                        },
                        {
                            "id": "Button_2",
                            "name": "btn_gameRule",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "interactive": false,
                            "x": 67,
                            "y": 1025,
                            "height": 64,
                            "width": 64,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'gamerule_disable.png',
                                out: 'gamerule_disable.png',
                                down: 'gamerule_disable.png',
                                disable: 'gamerule_disable.png',
                                enable: 'gamerule_disable.png',
                                hover: 'gamerule_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_3",
                            "name": "btn_sound",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 130,
                            "y": 1025,
                            "height": 60,
                            "width": 60,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'sound_up.png',
                                out: 'sound_up.png',
                                down: 'sound_down.png',
                                disable: 'sound_disable.png',
                                enable: 'sound_up.png',
                                hover: 'sound_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_3",
                            "name": "btn_soundDisable",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 130,
                            "y": 1025,
                            "height": 60,
                            "width": 60,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'soundoff_disable.png',   
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_4",
                            "name": "btn_soundOff",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 130,
                            "y": 1025,
                            "height": 60,
                            "width": 60,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'soundoff_up.png',
                                out: 'soundoff_up.png',
                                down: 'soundoff_down.png',
                                disable: 'soundoff_disable.png',
                                enable: 'soundoff_up.png',
                                hover: 'soundoff_over.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "name": "mobileViewBottomBArImage1FG",
                            "image": "mobileViewBottomBarImage1",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "filterTypes": [],
                            "visible": true,
                            "width": 1920,
                            "height": 150,
                            "x": 0,
                            "y": 860
                        },

                        {
                            "name": "mobileViewBottomBArImage2FG",
                            "image": "mobileViewBottomBarImage2",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "filterTypes": [],
                            "visible": true,
                            "width": 1920,
                            "height": 70,
                            "x": 0,
                            "y": 1010
                        },
                        {
                            "name": "mobileViewBottomBArLineImageFG_1",
                            "image": "bottomBarLineFG",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "filterTypes": [],
                            "visible": true,
                            "width": 4,
                            "height": 130,
                            "x": 270,
                            "y": 872
                        },

                        {
                            "name": "mobileViewBottomBArLineImageFG_2",
                            "image": "bottomBarLineFG",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "filterTypes": [],
                            "visible": true,
                            "width": 4,
                            "height": 130,
                            "x": 940,
                            "y": 872
                        },
                        {
                            "name": "mobileViewBottomBArLineImageFG_3",
                            "image": "bottomBarLineFG",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "filterTypes": [],
                            "visible": true,
                            "width": 4,
                            "height": 130,
                            "x": 1640,
                            "y": 872,
                        },
                        {
                            "id": "text_1_mobile",
                            "name": "text_FreeGame_label_mobileFG",
                            "type": "Text",
                            "x": 429,
                            "y": 940,
                            "width": 490,
                            "text": "freegameText1",
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 50,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_2_mobile",
                            "name": "text_FreeGame_value1_mobileFG",
                            "type": "Text",
                            "x": 680,
                            "y": 940,
                            "width": 806,
                            "text": "00",
                            "visible": true,
                            "layout": true,
                            "uimode": "mobile",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 50,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_3_mobile",
                            "name": "text_FreeGame_OF_label_mobileFG",
                            "type": "Text",
                            "x": 698,
                            "y": 940,
                            "visible": true,
                            "width": 90,
                            "text": "freegameText3",
                            "layout": true,
                            "uimode": "mobile",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 50,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_4_mobile",
                            "name": "text_FreeGame_value2_mobileFG",
                            "type": "Text",
                            "x": 830,
                            "y": 940,
                            "width": 76,
                            "text": "",
                            "visible": true,
                            "layout": true,
                            "uimode": "mobile",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 50,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },


                        {
                            "id": "text_5_mobile",
                            "name": "text_TotalWin_label_mobileFG",
                            "type": "Text",
                            "x": 1400,
                            "y": 940,
                            "width": 490,
                            "visible": false,
                            "layout": true,
                            "uimode": "mobile",
                            "text": "freegameText5",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 50,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_6_mobile",
                            "name": "text_TotalWin_value_mobileFG",
                            "type": "Text",
                            "x": 1308,
                            "y": 940,
                            "width": 820,
                            "layout": true,
                            "uimode": "mobile",
                            "text": "00",
                            "visible": true,
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 50,
                                fill: ['#ffffff'],
                                fontWeight: 'bold',
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "Button_M4",
                            "name": "btn_autoplayFG",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "layout": true,
                            "uimode": "mobile",
                            "interactive": false,
                            "x": 1760,
                            "y": 890,
                            "height": 81,
                            "width": 88,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'mobilehamburger_disable.png',
                                out: 'mobilehamburger_disable.png',
                                down: 'mobilehamburger_disable.png',
                                disable: 'mobilehamburger_disable.png',
                                enable: 'mobilehamburger_disable.png',
                                hover: 'mobilehamburger_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_M5",
                            "name": "btn_homeFG",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "layout": true,
                            "uimode": "mobile",
                            "interactive": false,
                            "x": 80,
                            "y": 890,
                            "height": 94,
                            "width": 102,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'mobilehome_disable.png',
                                out: 'mobilehome_disable.png',
                                down: 'mobilehome_disable.png',
                                disable: 'mobilehome_disable.png',
                                enable: 'mobilehome_disable.png',
                                hover: 'mobilehome_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "BMHorizontalGridContainerTag",
                            "name": "HorizontalGridContainer",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                        {
                            "id": "text_7_mobile",
                            "name": "Mobiletext_balance_labelFG",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "x": 170,
                            "y": 1050,
                            "width": 480,
                            "text": "buttonPanelText_3",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_8_mobile",
                            "name": "Mobiletext_mobColonSymbol2FG",
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "type": "Text",
                            "x": 315,
                            "y": 1048,
                            "width": 18,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_9_mobile",
                            "name": "Mobiletext_balance_valueFG",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "x": 330,
                            "y": 1050,
                            "width": 210,
                            "text": "",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "text_10_mobile",
                            "name": "Mobiletext_bet_labelFG",
                            "type": "Text",
                            "layout": true,
                            "visible": true,
                            "uimode": "mobile",
                            "x": 1683,
                            "y": 1050,
                            "width": 250,
                            "text": "buttonPanelText_1",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_11_mobile",
                            "name": "Mobiletext_mobColonSymbol3FG",
                            "layout": true,
                            "visible": true,
                            "uimode": "mobile",
                            "type": "Text",
                            "x": 1693,
                            "y": 1048,
                            "width": 18,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_12_mobile",
                            "name": "Mobiletext_bet_valueFG",
                            "type": "Text",
                            "layout": true,
                            "visible": true,
                            "uimode": "mobile",
                            "x": 1700,
                            "y": 1050,
                            "width": 100,
                            "text": "MobViewButtonPanelText3",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fill: ['#ffffff'],

                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "name": "FG_textManyWays_Image_Desktop",
                            "image": "manywaysTextImage",
                            "type": "Image",
                            "layout": true,
                            "uimode": "desktop",
                            "class": "",
                            "parentLayer": "baseLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 131,
                            "height": 43,
                            "x": 1022,
                            "y": 44,
                        },
                        {
                            "name": "FG_textManyWays_Image_mobile",
                            "image": "manywaysTextImage",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "class": "",
                            "parentLayer": "baseLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 131,
                            "height": 43,
                            "x": 1022,
                            "y": 44,
                        },
                        {
                            "id": "text_15_mobile",
                            "name": "Mobiletext_win_value_FG",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "x": 1068,
                            "y": 940,
                            "width": 200,
                            "text": "MobViewButtonPanelText1",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 60,
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "FG_BitMapText_1_desktop",
                            "name": "FG_manywaysText_desktop",
                            "type": "BitMapText",
                            "x": 958,
                            "y": -152,
                            "width": 180,
                            "text": "0",
                            "visible": true,
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "layout": true,
                            "uimode": "desktop",
                            "textStyle": {
                                font: '439px num-export',
                                letterSpacing: -15,
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "name": "multiplier_text_desktop",
                            "image": "multiplier",
                            "type": "Image",
                            "class": "",
                            "visible": true,
                            "layout": false,
                            "uimode": "desktop",
                            "width": 186,
                            "height": 34,
                            "x": 1718,
                            "y": 556,
                        },
                        {
                            "name": "multiplier_text_mobile",
                            "image": "multiplier",
                            "type": "Image",
                            "class": "",
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "width": 186,
                            "height": 34,
                            "x": 1718,
                            "y": 556,
                        },
                       
                        {
                            "id": "FG_BitMapText_1_mobile",
                            "name": "FG_manywaysText_mobile",
                            "type": "BitMapText",
                            "x": 960,
                            "y": -152,
                            "width": 180,
                            "text": "0",
                            "visible": true,
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "layout": true,
                            "uimode": "mobile",
                            "textStyle": {
                                font: '439px num-export',
                                letterSpacing: -15,
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "multiplierContainerTag",
                            "name": "Multiplier",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },

                        {
                            "name": "FG_bugFLies_Anim_desktop",
                            "type": "Animation",
                            "width": 960,
                            "height": 540,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "FG_bug_flies_1",
                            "animationSpeed": 0.2,
                            "playing": true,
                            "loop": true,
                            "visible": true,
                            "anchor": [0, 0],
                            "x": 0,
                            "y": 0,
                            "animations": {
                                "anim": ["FG_bug_flies_1", "FG_bug_flies_2", "FG_bug_flies_3", "FG_bug_flies_4"],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "name": "FG_reTrigger_blast_Anim_desktop",
                            "type": "Animation",
                            "width": 960,
                            "height": 540,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "FG_reTrigger",
                            "animationSpeed": 0.9,
                            "playing": true,
                            "loop": false,
                            "visible": false,
                            "anchor": [0, 0],
                            "x": 842,
                            "y": 912,
                            "animations": {
                                "anim": ["FG_reTrigger"],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "name": "FG_reTrigger_blast_Anim_mobile",
                            "type": "Animation",
                            "width": 960,
                            "height": 540,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "FG_reTrigger",
                            "animationSpeed": 0.9,
                            "playing": true,
                            "loop": false,
                            "visible": false,
                            "anchor": [0, 0],
                            "x": 845,
                            "y": 893,
                            "animations": {
                                "anim": ["FG_reTrigger"],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                       
                        {
                            "id": "winCelebrationContainerTag",
                            "name": "WinCelebration",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                        {
                            "id": "winShowerContainerTag",
                            "name": "WinShower",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },

                        {
                            "name": "freeGameBlackScreen",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "visible": false,
                            "alpha": 1,
                            "color": "0x000000",
                            "x": 0,
                            "y": 0,
                            "width": 1920,
                            "height": 1080,
                        },
                        {
                            "name": "freeGameBlackScreenPortrait",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "visible": false,
                            "alpha": 1,
                            "color": "0x000000",
                            "x": 0,
                            "y": 0,
                            "width": 1080,
                            "height": 1920,
                        },
                        {
                            "id": "SoundText",
                            "name": "SoundText",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                    ]
                },
            ]
        }
    ]
}