import React from "react";
import { objectTypes } from "../../../core/components/buttonpanel/interface/Ibuttons";


interface IframeworkCanvasAutoplay {
    data: {}

}

export const frameworkCanvasAutoplay: IframeworkCanvasAutoplay = {

    data: {
        "COMPONENTS": [


            {
                "id": "autoplayHeading",
                "name": "autoplayHeading",
                "type": "Text",
                "x": 955,
                "y": 191,
                "width": 1000,
                "visible": true,
                "text": "autoplayText_25",
                "scaleToFit": true,
                "anchor": [0.5, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 50,
                    fontWeight: 'bold',
                    fill: '#ffffff',
                },
            },
            {
                "id": "autoplayButton1",
                "name": "autoplayButton1",
                "type": objectTypes.Sprite,
                "interactive": false,
                "x": 466,
                "y": 274,
                "width": 124,
                "height": 66,
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'autoplay_btn_up.png',
                    out: 'autoplay_btn_up.png',
                    down: 'autoplay_btn_over.png',
                    disable: 'autoplay_btn_up.png',
                    enable: 'autoplay_btn_up.png',
                    hover: 'autoplay_btn_up.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "autoplayButtonText1",
                "name": "autoplayButtonText1",
                "type": "Text",
                "x": 466,
                "y": 274,
                "width": 60,
                "height": 50,
                "text": "    ",
                "anchor": [0.5, 0.5],
                "visible": true,
                "scaleToFit": true,
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 40,
                    fontStyle: 'normal',
                    fontWeight: 'bold',
                    fill: ['#ffffff'],
                },
            },
            {
                "id": "autoplayButton2",
                "name": "autoplayButton2",
                "type": objectTypes.Sprite,
                "interactive": false,
                "x": 590,
                "y": 274,
                "width": 124,
                "height": 66,
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'autoplay_btn_up.png',
                    out: 'autoplay_btn_up.png',
                    down: 'autoplay_btn_over.png',
                    disable: 'autoplay_btn_up.png',
                    enable: 'autoplay_btn_up.png',
                    hover: 'autoplay_btn_up.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "autoplayButtonText2",
                "name": "autoplayButtonText2",
                "type": "Text",
                "x": 590,
                "y": 274,
                "width": 60,
                "height": 50,
                "text": "     ",
                "anchor": [0.5, 0.5],
                "visible": true,
                "scaleToFit": true,
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 40,
                    fontStyle: 'normal',
                    fontWeight: 'bold',
                    fill: ['#ffffff'],
                },
            },
            {
                "id": "autoplayButton3",
                "name": "autoplayButton3",
                "type": objectTypes.Sprite,
                "interactive": true,
                "x": 714,
                "y": 274,
                "width": 124,
                "height": 66,
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'autoplay_btn_up.png',
                    out: 'autoplay_btn_up.png',
                    down: 'autoplay_btn_over.png',
                    disable: 'autoplay_btn_up.png',
                    enable: 'autoplay_btn_up.png',
                    hover: 'autoplay_btn_up.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "autoplayButtonText3",
                "name": "autoplayButtonText3",
                "type": "Text",
                "x": 714,
                "y": 274,
                "width": 60,
                "height": 50,
                "text": "     ",
                "anchor": [0.5, 0.5],
                "visible": true,
                "scaleToFit": true,
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 40,
                    fontStyle: 'normal',
                    fontWeight: 'bold',
                    fill: ['#ffffff'],
                },
            },
            {
                "id": "autoplayButton4",
                "name": "autoplayButton4",
                "type": objectTypes.Sprite,
                "interactive": true,
                "x": 838,
                "y": 274,
                "width": 124,
                "height": 66,
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'autoplay_btn_up.png',
                    out: 'autoplay_btn_up.png',
                    down: 'autoplay_btn_over.png',
                    disable: 'autoplay_btn_up.png',
                    enable: 'autoplay_btn_up.png',
                    hover: 'autoplay_btn_up.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "autoplayButtonText4",
                "name": "autoplayButtonText4",
                "type": "Text",
                "x": 838,
                "y": 274,
                "width": 60,
                "height": 50,
                "text": "     ",
                "anchor": [0.5, 0.5],
                "visible": true,
                "scaleToFit": true,
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 40,
                    fontStyle: 'normal',
                    fontWeight: 'bold',
                    fill: ['#ffffff'],
                },
            },
            {
                "id": "autoplayButton5",
                "name": "autoplayButton5",
                "type": objectTypes.Sprite,
                "interactive": true,
                "x": 962,
                "y": 274,
                "width": 124,
                "height": 66,
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'autoplay_btn_up.png',
                    out: 'autoplay_btn_up.png',
                    down: 'autoplay_btn_over.png',
                    disable: 'autoplay_btn_up.png',
                    enable: 'autoplay_btn_up.png',
                    hover: 'autoplay_btn_up.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "autoplayButtonText5",
                "name": "autoplayButtonText5",
                "type": "Text",
                "x": 962,
                "y": 274,
                "width": 60,
                "height": 50,
                "text": "     ",
                "anchor": [0.5, 0.5],
                "visible": true,
                "scaleToFit": true,
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 40,
                    fontStyle: 'normal',
                    fontWeight: 'bold',
                    fill: ['#ffffff'],
                },
            },
            {
                "id": "autoplayButton6",
                "name": "autoplayButton6",
                "type": objectTypes.Sprite,
                "interactive": true,
                "x": 1086,
                "y": 274,
                "width": 124,
                "height": 66,
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'autoplay_btn_up.png',
                    out: 'autoplay_btn_up.png',
                    down: 'autoplay_btn_over.png',
                    disable: 'autoplay_btn_up.png',
                    enable: 'autoplay_btn_up.png',
                    hover: 'autoplay_btn_up.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "autoplayButtonText6",
                "name": "autoplayButtonText6",
                "type": "Text",
                "x": 1086,
                "y": 274,
                "width": 67,
                "height": 50,
                "text": "      ",
                "anchor": [0.5, 0.5],
                "visible": true,
                "scaleToFit": true,
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 40,
                    fontStyle: 'normal',
                    fontWeight: 'bold',
                    fill: ['#ffffff'],
                },
            },
            {
                "id": "autoplayButton7",
                "name": "autoplayButton7",
                "type": objectTypes.Sprite,
                "interactive": true,
                "x": 1210,
                "y": 274,
                "width": 124,
                "height": 66,
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'autoplay_btn_up.png',
                    out: 'autoplay_btn_up.png',
                    down: 'autoplay_btn_over.png',
                    disable: 'autoplay_btn_up.png',
                    enable: 'autoplay_btn_up.png',
                    hover: 'autoplay_btn_up.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "autoplayButtonText7",
                "name": "autoplayButtonText7",
                "type": "Text",
                "x": 1210,
                "y": 274,
                "width": 67,
                "height": 50,
                "text": "      ",
                "anchor": [0.5, 0.5],
                "visible": true,
                "scaleToFit": true,
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 40,
                    fontStyle: 'normal',
                    fontWeight: 'bold',
                    fill: ['#ffffff'],
                },
            },
            {
                "id": "autoplayButton8",
                "name": "autoplayButton8",
                "type": objectTypes.Sprite,
                "interactive": true,
                "x": 1334,
                "y": 274,
                "width": 124,
                "height": 66,
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'autoplay_btn_up.png',
                    out: 'autoplay_btn_up.png',
                    down: 'autoplay_btn_over.png',
                    disable: 'autoplay_btn_up.png',
                    enable: 'autoplay_btn_up.png',
                    hover: 'autoplay_btn_up.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "autoplayButtonText8",
                "name": "autoplayButtonText8",
                "type": "Text",
                "x": 1334,
                "y": 274,
                "width": 67,
                "height": 50,
                "text": "     ",
                "anchor": [0.5, 0.5],
                "visible": true,
                "scaleToFit": true,
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 40,
                    fontStyle: 'normal',
                    fontWeight: 'bold',
                    fill: ['#ffffff'],
                },
            },
            {
                "id": "autoplayButton9",
                "name": "autoplayButton9",
                "type": objectTypes.Sprite,
                "interactive": true,
                "x": 1458,
                "y": 274,
                "width": 124,
                "height": 66,
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'autoplay_btn_up.png',
                    out: 'autoplay_btn_up.png',
                    down: 'autoplay_btn_over.png',
                    disable: 'autoplay_btn_up.png',
                    enable: 'autoplay_btn_up.png',
                    hover: 'autoplay_btn_up.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "autoplayButtonText9",
                "name": "autoplayButtonText9",
                "type": "Text",
                "x": 1458,
                "y": 274,
                "width": 67,
                "height": 50,
                "text": "      ",
                "anchor": [0.5, 0.5],
                "visible": true,
                "scaleToFit": true,
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 40,
                    fontStyle: 'normal',
                    fontWeight: 'bold',
                    fill: ['#ffffff'],
                },
            },
            {
                "id": "radioButtonOn",
                "name": "radioButtonOn",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 432,
                "y": 405,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_on.png',
                    out: 'raido_btn_on.png',
                    down: 'raido_btn_on.png',
                    disable: 'raido_btn_on.png',
                    enable: 'raido_btn_on.png',
                    hover: 'raido_btn_on.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "radioButtonOff",
                "name": "radioButtonOff",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 78,
                "height": 44,
                "x": 432,
                "y": 405,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'raido_btn_off.png',
                    out: 'raido_btn_off.png',
                    down: 'raido_btn_off.png',
                    disable: 'raido_btn_off.png',
                    enable: 'raido_btn_off.png',
                    hover: 'raido_btn_off.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },

            {
                "id": "radioButtonDisable",
                "name": "radioButtonDisable",
                "type": objectTypes.Sprite,
                "interactive": false,
                "width": 78,
                "height": 44,
                "x": 432,
                "y": 405,
                "text": "",
                "anchor": [0.5, 0.5],
                "visible": true,
                "buttonMode": false,
                "buttonState": {
                    up: 'raido_btn_disable.png',
                    out: 'raido_btn_disable.png',
                    down: 'raido_btn_disable.png',
                    disable: 'raido_btn_disable.png',
                    enable: 'raido_btn_disable.png',
                    hover: 'raido_btn_disable.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "stopAutoplayText",
                "name": "stopAutoplayText",
                "type": "Text",
                "x": 411,
                "y": 345,
                "width": 1500,
                "height": 400,
                "visible": true,
                "text": "autoplayText_2",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 36,
                    fill: '#ffffff',
                },
            },
            {
                "id": "onAnyWinText",
                "name": "onAnyWinText",
                "type": "Text",
                "x": 496,
                "y": 402,
                "width": 400,
                "height": 400,
                "visible": true,
                "text": "autoplayText_3",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 32,
                    fill: '#ffffff',
                },
            },


            {
                "name": "inputBox_1",
                "image": "meter.png",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": true,
                "width": 251,
                "height": 67,
                "x": 1230,
                "y": 450
            },
            {
                "name": "inputBox_2",
                "image": "meter.png",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": true,
                "width": 251,
                "height": 67,
                "x": 1230,
                "y": 568,
            },
            {
                "name": "inputBox_3",
                "image": "meter.png",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": true,
                "width": 251,
                "height": 67,
                "x": 1230,
                "y": 686
            },

            {
                "id": "sliderDot_inputBoxText",
                "name": "sliderDot_inputBoxText",
                "type": "Text",
                "x": 1354,
                "y": 482,
                "width": 400,
                "height": 400,
                "visible": true,
                "text": "0",
                "scaleToFit": true,
                "anchor": [0.5, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 32,
                    fontWeight: 'bold',
                    fill: '#ffffff',
                },
            },
            {
                "id": "sliderDot_2_inputBoxText",
                "name": "sliderDot_2_inputBoxText",
                "type": "Text",
                "x": 1354,
                "y": 602,
                "width": 400,
                "height": 400,
                "visible": true,
                "text": "0",
                "scaleToFit": true,
                "anchor": [0.5, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 32,
                    fontWeight: 'bold',
                    fill: '#ffffff',
                },
            },

            {
                "id": "sliderDot_3_inputBoxText",
                "name": "sliderDot_3_inputBoxText",
                "type": "Text",
                "x": 1354,
                "y": 718,
                "width": 400,
                "height": 400,
                "visible": true,
                "text": "0",
                "scaleToFit": true,
                "anchor": [0.5, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 32,
                    fontWeight: 'bold',
                    fill: '#ffffff',
                },
            },
            {
                "id": "sliderLineBG",
                "name": "sliderLineBG",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 743,
                "height": 18,
                "x": 400,
                "y": 479,
                "text": "",
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'slider_base.png',
                    out: 'slider_base.png',
                    down: 'slider_base.png',
                    disable: 'slider_base.png',
                    enable: 'slider_base.png',
                    hover: 'slider_base.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "sliderDotLine",
                "name": "sliderDotLine",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 743,
                "height": 18,
                "x": 400,
                "y": 479,
                "text": "",
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'slider_top.png',
                    out: 'slider_top.png',
                    down: 'slider_top.png',
                    disable: 'slider_top.png',
                    enable: 'slider_top.png',
                    hover: 'slider_top.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "name": "sliderDot",
                "image": "slider_dot.png",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": true,
                "width": 34,
                "height": 34,
                "x": 100,
                "y": 472
            },
            {
                "name": "sliderDot_disable",
                "image": "slider_dot_disable.png",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": false,
                "width": 34,
                "height": 34,
                "x": 400,
                "y": 472
            },
            {
                "id": "sliderLine_2BG",
                "name": "sliderLine_2BG",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 743,
                "height": 18,
                "x": 400,
                "y": 595,
                "text": "",
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'slider_base.png',
                    out: 'slider_base.png',
                    down: 'slider_base.png',
                    disable: 'slider_base.png',
                    enable: 'slider_base.png',
                    hover: 'slider_base.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "sliderDot_2Line",
                "name": "sliderDot_2Line",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 743,
                "height": 18,
                "x": 400,
                "y": 595,
                "text": "",
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'slider_top.png',
                    out: 'slider_top.png',
                    down: 'slider_top.png',
                    disable: 'slider_top.png',
                    enable: 'slider_top.png',
                    hover: 'slider_top.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "name": "sliderDot_2",
                "image": "slider_dot.png",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": true,
                "width": 34,
                "height": 34,
                "x": 400,
                "y": 588
            },
            {
                "name": "sliderDot_2_disable",
                "image": "slider_dot_disable.png",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": false,
                "width": 34,
                "height": 34,
                "x": 400,
                "y": 588
            },
            {
                "id": "sliderLine_3BG",
                "name": "sliderLine_3BG",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 743,
                "height": 18,
                "x": 400,
                "y": 710,
                "text": "",
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'slider_base.png',
                    out: 'slider_base.png',
                    down: 'slider_base.png',
                    disable: 'slider_base.png',
                    enable: 'slider_base.png',
                    hover: 'slider_base.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },

            {
                "id": "sliderDot_3Line",
                "name": "sliderDot_3Line",
                "type": objectTypes.Sprite,
                "interactive": true,
                "width": 743,
                "height": 18,
                "x": 400,
                "y": 710,
                "text": "",
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'slider_top.png',
                    out: 'slider_top.png',
                    down: 'slider_top.png',
                    disable: 'slider_top.png',
                    enable: 'slider_top.png',
                    hover: 'slider_top.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "name": "sliderDot_3",
                "image": "slider_dot.png",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": true,
                "width": 34,
                "height": 34,
                "x": 400,
                "y": 704
            },
            {
                "name": "sliderDot_3_disable",
                "image": "slider_dot_disable.png",
                "type": "Image",
                "class": "",
                "filterTypes": [],
                "visible": false,
                "width": 34,
                "height": 34,
                "x": 400,
                "y": 704
            },

            {
                "id": "ifSingleWinExceedText",
                "name": "ifSingleWinExceedText",
                "type": "Text",
                "x": 430,
                "y": 526,
                "width": 1000,
                "height": 400,
                "visible": true,
                "text": "autoplayText_6",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 32,
                    fill: '#ffffff',
                },
            },
            {
                "id": "ifBalanceIncreaseByText",
                "name": "ifBalanceIncreaseByText",
                "type": "Text",
                "x": 430,
                "y": 645,
                "width": 1000,
                "height": 400,
                "visible": true,
                "text": "autoplayText_7",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 32,
                    fill: '#ffffff',
                },
            },
            {
                "id": "ifBalanceDecreaseByText",
                "name": "ifBalanceDecreaseByText",
                "type": "Text",
                "x": 430,
                "y": 749,
                "width": 1000,
                "height": 400,
                "visible": true,
                "text": "autoplayText_8",
                "scaleToFit": true,
                "anchor": [0, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 32,
                    fill: '#ffffff',
                },
            },
            {
                "id": "autoplay_StartButton",
                "name": "autoplay_StartButton",
                "type": objectTypes.Sprite,
                "interactive": false,
                "x": 971,
                "y": 814,
                "height": 76,
                "width": 168,
                "text": "",
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'start_btn_up.png',
                    out: 'start_btn_up.png',
                    down: 'start_btn_down.png',
                    disable: 'start_btn_disable.png',
                    enable: 'start_btn_up.png',
                    hover: 'start_btn_over.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "Button_2",
                "name": "autoplay_CancelButton",
                "type": objectTypes.Sprite,
                "interactive": true,
                "x": 781,
                "y": 814,
                "height": 76,
                "width": 168,
                "text": "",
                "visible": true,
                "buttonMode": true,
                "buttonState": {
                    up: 'cancel_btn_up.png',
                    out: 'cancel_btn_up.png',
                    down: 'cancel_btn_down.png',
                    disable: 'cancel_btn_disable.png',
                    enable: 'cancel_btn_up.png',
                    hover: 'cancel_btn_over.png'
                },
                "hitareaVisible": false,
                "shapeVisible": false,
                "shape": {}
            },
            {
                "id": "text_1",
                "name": "autoplay_text_start_label",
                "type": "Text",
                "x": 1055,
                "y": 852,
                "visible": true,
                "text": "autoplayText_20",
                "scaleToFit": true,
                "width": 210,
                "anchor": [0.5, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 26,
                    fontWeight: 'bold',
                    fill: ['#ffffff', '#ffffff', '#ffffff'],
                },
                "parentLayer": "specialAnimationLayer",
            },
            {
                "id": "text_2",
                "name": "autoplay_text_cancel_label",
                "type": "Text",
                "x": 866,
                "y": 852,
                "visible": true,
                "text": "autoplayText_21",
                "scaleToFit": true,
                "anchor": [0.5, 0.5],
                "textStyle": {
                    fontFamily: 'Arial',
                    fontSize: 26,
                    fontWeight: 'bold',
                    fill: ['#ffffff', '#ffffff', '#ffffff'],
                },
                "parentLayer": "specialAnimationLayer",
            },

        ],
    }
};

export const CanvasAutoplayConfigurationContext = React.createContext(
    {}
);