import { frameworkLandingSymbol } from "../../../core/components/landingsymbol/configuration/landingsymbolconfiguration";
import { configGame } from "../../../data/config";

frameworkLandingSymbol.data = {
    "SYMBOL_WIDTH": configGame.SYMBOL_WIDTH,
    "SYMBOL_HEIGHT": configGame.SYMBOL_HEIGHT,
    "SINGLE_SYMBOL_DELAY_IN_ANIM": 1,
    "SYMBOL_ANIMATION_GRP_WISE": false,
    "SYMBOL_ANIMATION_EFFECT": [],

    "symbols": [],
    "symbolsAnimation": [
        {
            "id": "1",
            "name": "symbolF_2",
            "width": 206,
            "height": 308,
            "offsetX":30,
            "offsetY": 30,

            "child": [  
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "F_base_2",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 122,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "F_base_2",
                        "loop": false,
                        "timeScale": 1

                    },
                },

            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "2",
            "name": "symbolF_3",
            "width": 206,
            "height": 206,
            "offsetX": 30,
            "offsetY": 30,
            "child": [

                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "F_base_3",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 73,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "F_base_3",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "3",
            "name": "symbolF_4",
            "width": 206,
            "height": 154,
            "offsetX": 30,
            "offsetY": 30,
            "child": [

                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "F_base_4",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 47,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "F_base_4",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "4",
            "name": "symbolF_5",
            "width": 206,
            "height": 124,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "F_base_5",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 32,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "F_base_5",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "5",
            "name": "symbolF_6",
            "width": 206,
            "height": 104,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "F_base_6",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 22,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "F_base_6",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "6",
            "name": "symbolF_7",
            "width": 206,
            "height": 88,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "F_base_7",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 16,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "F_base_7",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },


        {
            "id": "7",
            "name": "symbolI_2",
            "width": 206,
            "height": 308,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "I_base_2",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 124,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "I_base_2",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "8",
            "name": "symbolI_3",
            "width": 206,
            "height": 206,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "I_base_3",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 73,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "I_base_3",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "9",
            "name": "symbolI_4",
            "width": 206,
            "height": 154,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "I_base_4",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 47,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "I_base_4",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "10",
            "name": "symbolI_5",
            "width": 206,
            "height": 124,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "I_base_5",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 32,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "I_base_5",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "11",
            "name": "symbolI_6",
            "width": 206,
            "height": 104,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "I_base_6",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 22,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "I_base_6",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "12",
            "name": "symbolI_7",
            "width": 206,
            "height": 88,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "I_base_7",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 16,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "I_base_7",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },


        {
            "id": "13",
            "name": "symbolR_2",
            "width": 206,
            "height": 308,
            "offsetX": 30,
            "offsetY": 30,
            "child": [  
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "R_base_2",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 124,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "R_base_2",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "14",
            "name": "symbolR_3",
            "width": 206,
            "height": 206,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "R_base_3",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 73,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "R_base_3",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "15",
            "name": "symbolR_4",
            "width": 206,
            "height": 154,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "anchor":[0,0],
                    "spineAnimName": "R_base_4",
                    "x": 74,
                    "y": 47,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "R_base_4",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "16",
            "name": "symbolR_5",
            "width": 206,
            "height": 124,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "R_base_5",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 32,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "R_base_5",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "17",
            "name": "symbolR_6",
            "width": 206,
            "height": 104,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "R_base_6",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 22,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "R_base_6",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "18",
            "name": "symbolR_7",
            "width": 206,
            "height": 88,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "R_base_7",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 16,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "R_base_7",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },


        {
            "id": "19",
            "name": "symbolE_2",
            "width": 206,
            "height": 308,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "E_base_2",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 124,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "E_base_2",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "20",
            "name": "symbolE_3",
            "width": 206,
            "height": 206,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {    
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "E_base_3",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 73,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "E_base_3",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "21",
            "name": "symbolE_4",
            "width": 206,
            "height": 154,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "E_base_4",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 47,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "E_base_4",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "22",
            "name": "symbolE_5",
            "width": 206,
            "height": 124,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "E_base_5",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 32,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "E_base_5",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "23",
            "name": "symbolE_6",
            "width": 206,
            "height": 104,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "E_base_6",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 22,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "E_base_6",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "24",
            "name": "symbolE_7",
            "width": 206,
            "height": 88,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "E_base_7",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 16,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "E_base_7",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "25",
            "name": "symbolExtraScatter_2",
            "width": 206,
            "height": 308,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "+5_base_2",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 124,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "+5_base_2",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "26",
            "name": "symbolExtraScatter_3",
            "width": 206,
            "height": 206,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "+5_base_3",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 73,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "+5_base_3",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "27",
            "name": "symbolExtraScatter_4",
            "width": 206,
            "height": 154,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "+5_base_4",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 47,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "+5_base_4",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "28",
            "name": "symbolExtraScatter_5",
            "width": 206,
            "height": 124,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "+5_base_5",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 32,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "+5_base_5",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "29",
            "name": "symbolExtraScatter_6",
            "width": 206,
            "height": 104,
            "offsetX": 30,
            "offsetY": 30,
            "child": [

                {   
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "+5_base_6",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 22,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "+5_base_6",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
        {
            "id": "30",
            "name": "symbolExtraScatter_7",
            "width": 206,
            "height": 88,
            "offsetX": 30,
            "offsetY": 30,
            "child": [
                {
                    "type": "Spine",
                    "width": 208,
                    "height": 310,
                    "image": "fire",
                    "animationSpeed": 0.2,
                    "playing": false,
                    "loop": false,
                    "visible": true,
                    "effectType": "abc",
                    "maskHeight": 336,
                    "spineAnimName": "+5_base_7",
                    "anchor":[0,0],
                    "x": 74,
                    "y": 16,
                    "spinedata": {
                        "spinename": "fire",
                        "animationname": "+5_base_7",
                        "loop": false,
                        "timeScale": 1

                    },
                },
            ],
            "loop": true,
            "visible": true,
        },
    ],

}